### ISSUE TITLE
Add Support for Bookmarks

### ISSUE THREAD

**Issue by erauner12** [snezhig/obsidian-front-matter-title#104]
I know this feature is brand new, just wanted to log a request to support it in the same way that starred files (since they will eventually replace it) 🙂

**Comment by snezhig** [comment]
Is it actual issue?

**Comment by erauner12** [comment]
I suppose this might not actually be an issue if the bookmark is named when it is created?

**Comment by redactedscribe** [comment]
Naming it manually on creation is one way, but then keeping the `title:` and the bookmark name in alignment would become a thing. This plugin should ideally just read the `title:` and display it in the UI like it does for other areas of the interface. If the bookmark is manually named, then that should probably override whatever the `title:` is set to.
