### ISSUE TITLE
Cannot open files on mobile when active

### ISSUE THREAD

**Issue by JaCoB1123** [snezhig/obsidian-front-matter-title#108]
Hi,

I just noticed that I can't open a file from the file explorer on Android when "Replace shown titles in the file explorer" is active. Tapping an element does nothing. When I disable the plugin or just the "Explorer" Feature it works again.

Other than that, I really like the plugin as I've just migrated from Trilium and have slashes in my titles everywhere 😆

**Comment by snezhig** [comment]
Can you give me some examples of your files? Your app version?
I do not have such bug.

**Comment by JaCoB1123** [comment]
I just tried reproducing it again and was unable to do so. Closing for now.
