### ISSUE TITLE
Use regex to replace part of the file name

### ISSUE THREAD

**Issue by ss818** [snezhig/obsidian-front-matter-title#110]
The format of my note name is "_ClassificationNumber timestamp file name_", for example "_001 202304211299 love and peace_", can I use regularization to make it displayed as "_love and peace_".

**Comment by hiteshbedre** [comment]
Yes, with a substitution regularization you make it.
Pattern: `(\d+(?:\s\d+)\s)`
Replace With empty string.
Here is quick demo: https://regex101.com/r/1t5yi1/1

**Comment by ss818** [comment]
Thank you very much, this plugin is awesome.
