### ISSUE TITLE
The text is not fully displayed in the file manager.

### ISSUE THREAD

**Issue by ivkorolyov** [snezhig/obsidian-front-matter-title#113]
Hello,
Is it possible to make the text fully displayed? We are talking about a file manager located on the left. 
Right now, the text is displayed in one line, as shown in the screenshot. And it's not convenient.
Thank you.
![Screenshot_20230522_140336_Obsidian](https://github.com/snezhig/obsidian-front-matter-title/assets/50589503/f6b568db-9df1-438f-a60b-db5e3474d1fd)

**Comment by snezhig** [comment]
Hi. It's common behavior of the app. But I can try to find out if it is possible to change.

**Comment by basilioss** [comment]
Minimal Theme Settings plugin has an option to disable file names trimming in sidebars

**Comment by ivkorolyov** [comment]
> Minimal Theme Settings plugin has an option to disable file names trimming in sidebars
