### ISSUE TITLE
Feature request: play well with folder note plugins

### ISSUE THREAD

**Issue by pm64** [snezhig/obsidian-front-matter-title#115]
This plugin has become a crucial part of my workflow, since it liberates me from the restrictions of filenames, allowing a note that would otherwise have to be named "dotNET", for example, to appear as ".NET", and supports tons of other use cases.

It would be amazing for this plugin to work with folder note plugins (for example, https://github.com/LostPaul/obsidian-folder-notes and https://github.com/xpgo/obsidian-folder-note-plugin and https://github.com/aidenlx/alx-folder-note).

The idea with such plugins is that if a folder contains a file with a filename that is the same as the folder name (plus .md extension), the file is hidden from the user, and the containing folder "becomes" the note. The end result is a system where notes can have child notes.

To work with this plugin, the containing folder's name would need to be displayed as the title of the corresponding folder note. Currently this plugin doesn't affect folder names.

I know it's not a trivial ask, but I'm confident a feature/option like this would be extremely useful for many users.

**Comment by ivkorolyov** [comment]
Hello,
I would like the ability to create virtual folders directly from the title.
Example: 
```
title: virtual-folder/note
title: virtual-folder-note/virtual-folder/note
```
I'm sorry, I don't speak English. I hope my idea is clear.

**Comment by ivkorolyov** [comment]
Hello,
I would like the ability to create virtual folders directly from the title.
Example: 
```
title: virtual-folder/note
title: virtual-folder-note/virtual-folder/note
```
By analogy with tags.
![Uploading Screenshot_20230608_021231_Obsidian.jpg…]()

**Comment by ivkorolyov** [comment]
Hello,
I would like the ability to create virtual folders directly from the title.
Example: 
```
title: virtual-folder/note
title: virtual-folder-note/virtual-folder/note
```
By analogy with tags.
![Screenshot_20230608_021231_Obsidian](https://github.com/snezhig/obsidian-front-matter-title/assets/50589503/46ef81ee-ae00-41fa-8377-38ff5c0eeab8)
![Screenshot_20230608_021257_Obsidian](https://github.com/snezhig/obsidian-front-matter-title/assets/50589503/40bd950e-7da1-4686-9acc-86e0bfa684e7)

**Comment by ivkorolyov** [comment]
Hello,
I would like the ability to create virtual folders directly from the title.
Example: 
```
title: virtual-folder/note
title: virtual-folder-note/virtual-folder/note
```
"It looks like this if the function is turned on."
![Screenshot_20230608_022701_Obsidian](https://github.com/snezhig/obsidian-front-matter-title/assets/50589503/054ba3d6-e765-45dc-a97e-e083667dcc71)
![Screenshot_20230608_022758_Obsidian](https://github.com/snezhig/obsidian-front-matter-title/assets/50589503/a08beb80-e715-47cb-80e9-20c2ba4d447f)

"It looks like this if the function is turned off."
![Screenshot_20230608_022900_Obsidian](https://github.com/snezhig/obsidian-front-matter-title/assets/50589503/97997cc7-a11f-4384-8957-dd66662fa1f4)

**Comment by MaryDBurke01** [comment]
+1

**Comment by snezhig** [comment]
The author of https://github.com/LostPaul/obsidian-folder-notes knows about [api provider](https://github.com/snezhig/front-matter-plugin-api-provider). I think he will add support soon.
You can also try to open issues in the rest plugins to ask authors if they could use api provider to interact with my plugin.
