### ISSUE TITLE
[Bug] Files can't be opened from explorer when "Explorer sort" is activated

### ISSUE THREAD

**Issue by alltagsverstand** [snezhig/obsidian-front-matter-title#117]
With Obsidian 1.3.5. Also, no file preview is shown when hovering the file name. Deactivating the "explorer sort" function and restarting obsidian afterwards solves the problem.

**Comment by snezhig** [comment]
Hi!
Do you have another plugins? Have you tried to repeat this without another community plugins?
I have just tried to repeat this and could open any file with "explorer sort".
