### ISSUE TITLE
[Feature Request] Compatible with recent-files-obsidian

### ISSUE THREAD

**Issue by olapEin** [Snezhig/obsidian-front-matter-title#12]
This plugin is important for using only the ZK ID as the filename. Thank you so much for what you did.

I have a request: compatible with recent-files-obsidian. I need to go through my recent notes. The recent-files-obsidian is here: <https://github.com/tgrosinger/recent-files-obsidian>.

Thanks.

**Comment by BigbadHort** [comment]
Mee too need it!!! Please!!!

**Comment by Snezhig** [comment]
@BigbadHort, @olapEin you can ask the plugin's author to use [api-provider](https://www.npmjs.com/package/front-matter-plugin-api-provider) and use my plugin's titles.
