### ISSUE TITLE
Better plugin description

### ISSUE THREAD

**Issue by Raboro** [snezhig/obsidian-front-matter-title#122]
So far there is no exact description for the plugin, both in the repository description and in the Readme.md. To give a better first contact to possible new users it would be useful to have a better description, what the plugin does exactly, what the key features are.

**Comment by nhan000** [comment]
Have you tried clicking these links in the readme? It can give you a pretty good idea of the plugin.

![image](https://github.com/snezhig/obsidian-front-matter-title/assets/85216095/975d2366-e209-4b15-9c2f-a816d31fecf0)

**Comment by snezhig** [comment]
I did some improvements in [3.4.0](https://github.com/snezhig/obsidian-front-matter-title/releases/tag/3.4.0)
