### ISSUE TITLE
Inline title display issue

### ISSUE THREAD

**Issue by mdSlash** [snezhig/obsidian-front-matter-title#123]
Hey there, thank you for this awesome plugin! There's a small issue with the inline title. Sometimes it shows the original file name instead of the frontmatter title, and other times it displays both the original title and the frontmatter title below it.

**Comment by snezhig** [comment]
Hi. Could you say me how to reproduce this? May be you do something specific? Or just record a video?

**Comment by MDslash** [comment]
Steps to reproduce:

1. Open two notes, one on the right and the other on the left.
2. Switch the note on the right side with the one on the left side and modify its `title`.
3. Switch between "reading view" and "editing mode".

https://github.com/snezhig/obsidian-front-matter-title/assets/128622475/5c973719-f64f-467d-aee6-7397ddc2f506

**Comment by snezhig** [comment]
I found a possible solution. It will be released soon.

**Comment by snezhig** [comment]
Should be fixed in [3.4.0](https://github.com/snezhig/obsidian-front-matter-title/releases/tag/3.4.0)

**Comment by snezhig** [comment]
Okay, I will try to find something.

**Comment by snezhig** [comment]
@MDslash what is you app version? Plugin version is 3.4.1? What is OS?

**Comment by MDslash** [comment]
@snezhig Front Matter Title v3.4.1, and I have other plugins.

SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.3.5
	Operating system: #1 SMP PREEMPT_DYNAMIC Thu, 06 Jul 2023 18:35:54 +0000 6.4.2-arch1-1

**Comment by snezhig** [comment]
Can you try to reproduce it with new [3.5.0](https://github.com/snezhig/obsidian-front-matter-title/releases/tag/3.5.0) version?

**Comment by Jmuccigr** [comment]
I'm still seeing this with 3.10.0 on a Mac. Both titles are always present. Works fine in iOS.
