### ISSUE TITLE
Let Eslint fix issues and push directly in CI in repo to automate manually fixing those issues 

### ISSUE THREAD

**Issue by Raboro** [snezhig/obsidian-front-matter-title#128]
If there are some Eslint style issues the build fails and you need to fix them manually.  But you can configure your Eslint to fix those issues and then push those fixes into the repo in CI via a GitHub Actions Bot. After that you can do the analysis again and check if all issues are fixed. 

For that you need to add a script in package.json to fix those issues and configure the buid.yml file to push those changes. You need to also enable in the repo settings under Actions > General - Workflow permissions Read and Write permissions so that the GH Actions Bot can actually push the changes.

![image](https://github.com/snezhig/obsidian-front-matter-title/assets/88288557/48332bae-acef-4d67-add8-6f04f38fb099)

**Comment by snezhig** [comment]
I will check it.
