### ISSUE TITLE
Compatibility with local graph

### ISSUE THREAD

**Issue by nicolaskruchten** [Snezhig/obsidian-front-matter-title#13]
Thanks for this excellent plugin! It works everywhere I'd like it to except for the page-level Graph View (i.e. not the vault-wide Graph View)... Is this something that could be added?

**Comment by Snezhig** [comment]
Thank you for the feedback.
I'n not sure I understand what you told about.
If you can give me more information to understand (with screenshots may be), I will discover what I can do with it.

**Comment by nicolaskruchten** [comment]
Sure, sorry I wasn't clear! For a given note, if you click on the three dots in the top-right corner to pull up the menu, there is the option to "Open local graph" which opens a graph-like view of the current note, plus notes that it links to and notes that link to it. This "local graph" is what I referred to as "page-level Graph View". 

When using your plugin, the notes in this local graph view are not displayed with their title from the front matter, and it would be awesome if they were! Please let me know if this is still not clear :)

**Comment by nicolaskruchten** [comment]
You know what, I just tried it again and it seems to work as I would like now, so perhaps I was doing something wrong before or I restarted and it cleared up. Sorry for the noise, and thanks again for the very handy plugin!

**Comment by Snezhig** [comment]
I understood.
But my plugin does not work with local-graph properly. For example it will not update the graph if you change title in your file. But I will try to fix it, so I reopen the issue.

**Comment by nicolaskruchten** [comment]
OK! Interestingly enough, as I've been working today with the local graph open, it seems to switch between working and not-working... The local graph for the note I was looking at when I closed the issue now no longer displays the names I was expecting. I'm not sure what changed in between: I added some notes, edited the title of one etc but I don't know specifically when it stopped working.

Thanks again!

**Comment by Snezhig** [comment]
Hi, you can try the [beta version](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/1.3.0-beta).
I have added support for local graph.

**Comment by nicolaskruchten** [comment]
Awesome! I'm not actually sure how to install a beta version though... any hints?

**Comment by Snezhig** [comment]
You can use [BRAT](https://github.com/TfTHacker/obsidian42-brat) plugin.

**Comment by Snezhig** [comment]
Hello.
You can just update this plugin in application.

**Comment by nicolaskruchten** [comment]
Looks great, thank you!
