### ISSUE TITLE
Plugin doesn't resolve boolean values

### ISSUE THREAD

**Issue by rk-terence** [snezhig/obsidian-front-matter-title#133]
Hi, I have just installed your plugin, and checked the examples you provided. Thank you for your awesome work! 

My use case is that I want to use a boolean value in the YAML frontmatter, for example
```markdown
---
draft: true
title: blabla
---
```
and the "common main template" I specified is `draft`. However, it seems that the plugin didn't resolve the value of `draft`; it displayed the original title in the explorer instead, whenever the `draft` value in the frontmatter is `true` or `false`. When I change `draft` to non-boolean values, it works.

When I use multiple keys in the frontmatter, i.e. `{{draft}} - {{title}}`, the resolved string will be `- {{title}}`.

I guess that there might be some bugs associated with boolean yaml frontmatter keys.

Looking forward to your reply~

**Comment by snezhig** [comment]
Hi, I will check it soon.

**Comment by snezhig** [comment]
Added in [3.4.0](https://github.com/snezhig/obsidian-front-matter-title/releases/tag/3.4.0)

**Comment by rk-terence** [comment]
Hello there!
Thanks for your quick response. I have installed the latest version (3.4.0), but I discovered that the problem still persists.

Here are some screenshots:

<img width="930" alt="image" src="https://github.com/snezhig/obsidian-front-matter-title/assets/28799257/205f0378-f110-46a0-ab18-03d8182cb930">

My settings for this plugin:

<img width="912" alt="image" src="https://github.com/snezhig/obsidian-front-matter-title/assets/28799257/1cad3115-9371-40c4-92ad-9c2a7653e148">

<img width="903" alt="image" src="https://github.com/snezhig/obsidian-front-matter-title/assets/28799257/56e41a4b-2226-403d-8d47-1d5721bd7e59">

The version of this plugin is:

<img width="651" alt="image" src="https://github.com/snezhig/obsidian-front-matter-title/assets/28799257/a58f618b-39b5-43de-b54a-805b29ae04b7">

I have also tried downloading the .zip package from the release page, and got the same result.

Are there any settings that I didn't use correctly? Thank you very much.

**Comment by snezhig** [comment]
I'm so sorry. I did not add it in config to enable. I'm going to release 3.4.1 today with fix.

**Comment by rk-terence** [comment]
> I'm so sorry. I did not add it in config to enable. I'm going to release 3.4.1 today with fix.

Thank you. There's no need to apologize. 😁

**Comment by snezhig** [comment]
Should be fixed now in 3.4.1.

**Comment by rk-terence** [comment]
> Should be fixed now in 3.4.1.

It worked! Thank you so much. This plugin helps me a lot in my workflow ❤️. Now I can quickly locate different markdown files based on their frontmatter values. Also, I think the processor functionality is awesome as it provides us with a way to postprocess the resolved value.

Thank you again for your awesome work!
