### ISSUE TITLE
Feature request: Remove empty brakets

### ISSUE THREAD

**Issue by raelb** [snezhig/obsidian-front-matter-title#137]
Thanks for nice plugin.

For example if template is like this:
`{{_basename}} [{{type}}]`
and type is not found, then it will just show `filename []`. So the trailing brackets such as (), or [], or trailing` - ` should be automatically removed

**Comment by snezhig** [comment]
Thank you.

You can try to use [Processor](https://github.com/snezhig/obsidian-front-matter-title/blob/master/docs/Processor.md) for this.

**Comment by snezhig** [comment]
Something like this `(\(|\[)\s*(\)|])`:

![изображение](https://github.com/snezhig/obsidian-front-matter-title/assets/3987716/6c1486f1-a345-4248-95dc-29bd995a0562)

**Comment by raelb** [comment]
Yes, that's just what I needed, thanks
