### ISSUE TITLE
Canvas zoom-out not implemented

### ISSUE THREAD

**Issue by thesofakillers** [snezhig/obsidian-front-matter-title#144]
As pointed out by @amorette-practicumfit in #106, when zooming out a canvas such that the content is replaced by file titles, the front-matter title is not used here. We were wondering if this is intended, and if it is not, whether it can be changed. See attached example: 
![image](https://github.com/snezhig/obsidian-front-matter-title/assets/26286291/4ebacf24-f550-4dad-bc5d-406ec3064d0e)

**Comment by snezhig** [comment]
I understand and I think that I know how to fix it.

**Comment by snezhig** [comment]
Implemented in [3.5.0](https://github.com/snezhig/obsidian-front-matter-title/releases/tag/3.5.0)

**Comment by thesofakillers** [comment]
Amazing. Thank you.
