### ISSUE TITLE
[Bug] Reloading causes creation of an empty page when 'create shown title in tabs enabled'

### ISSUE THREAD

**Issue by merrkry** [snezhig/obsidian-front-matter-title#152]
With "Features - Tabs - Replace shown title in tabs" enabled, reload Obsidian / re-enable the feature / reload plugin via command will create an empty page in left sidebar.

**Comment by snezhig** [comment]
Sorry, fixed in 3.5.1.

**Comment by snezhig** [comment]
Feel free to reopen or create a new one.
