### ISSUE TITLE
[Feature Request] use first item in list

### ISSUE THREAD

**Issue by nicolaskruchten** [Snezhig/obsidian-front-matter-title#16]
I've got this plugin configured to use `alias` as the meta title path, but some of my notes have multiple aliases... It would be great IMO if the plugin would pick up the `alias` value if there's only one, and if it picked up the first value if there are multiple.

**Comment by pat-richter** [comment]
Installed the plugin and this was exactly the first thing I thought about (since aliases already have many advantages in links, search, ...).

Thank you very much!

**Comment by Snezhig** [comment]
Hi, the [1.4.0 release](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/1.4.0) brings this feature.

**Comment by nicolaskruchten** [comment]
Thanks so much! What an excellent plugin :)
