### ISSUE TITLE
Duplicated entries in Quick Switcher.

### ISSUE THREAD

**Issue by amariusz** [snezhig/obsidian-front-matter-title#165]
When I search for a file with `title` attribute in Quick Switcher I'd expect one entry for file and one for alias. Instead there are two entries with the same contents. 

Looking for part of title:

![230811_132849_fmt_search_by_name](https://github.com/snezhig/obsidian-front-matter-title/assets/20703230/b57034ec-7631-49f0-9320-922e673b8414)

Looking for part of file name:
![230811_133817_search_by_id](https://github.com/snezhig/obsidian-front-matter-title/assets/20703230/90565fd6-d0a3-4bf1-8d22-7e2a83be162a)
In the screenshot above you can observe that part of the title string is highlighted although I'm searching for different text - part of ID.

BTW. Thank you very much for this plugin. What a brilliant idea!

Edit:
Current behaviour is a little bit confusing and not consistent with how Obsidian search for aliases work but has a benefit of showing title at all times. So maybe it's a feature? :)

**Comment by snezhig** [comment]
Plugins Quick Switcher Feature is the most strange and difficult feature with some side-effects.
I think about how to make it more understandable.

About your problem. When you type anything in QuickSwitcher the plugin try to replace filenames with aliases, but the application keeps bold part than makes them to seem strange and confusing, The only idea a have is try to remove highlighting.

**Comment by snezhig** [comment]
@amariusz Can you give me your plugin feature settings with templates? And a document example. I think there is an another problem with duplicates.

**Comment by amariusz** [comment]
Sure. I think you should be able to recreate scenario from screenshots with following files:

[data.zip](https://github.com/snezhig/obsidian-front-matter-title/files/12388539/data.zip)
[230811_132444-file-name-testing.md](https://github.com/snezhig/obsidian-front-matter-title/files/12388540/230811_132444-file-name-testing.md)

**Comment by snezhig** [comment]
@amariusz I got the problem, okay. It will be fixed.
