### ISSUE TITLE
Plugin causes problems with search bars 

### ISSUE THREAD

**Issue by Friedolito** [snezhig/obsidian-front-matter-title#167]
Since the newest update, obsidian-front-matter-title will block my command search bar (search bar appears, but no command can be selected) and the search bar for templates (Error: Templater Error: Cannot read properties of undefined (reading 'path')). 
Disabling the plug in and normal function is restored. 

I use: 
Obsmd 1.4.4
(Installer version: v1.3.5)
On a MacBook macOS Ventura 13.4

Happy to provide further information when needed.

**Comment by snezhig** [comment]
I think that I know the problem. Fix be fixed in 8 hours. Or 10.

**Comment by snezhig** [comment]
@Friedolito, try to update plugin. [3.6.2](https://github.com/snezhig/obsidian-front-matter-title/releases/tag/3.6.2) fixes it.

**Comment by Friedolito** [comment]
Amazing, it's gone! Thanks a lot!
