### ISSUE TITLE
Display error on hover window

### ISSUE THREAD

**Issue by jiajiala** [snezhig/obsidian-front-matter-title#168]

**Comment by jiajiala** [comment]
![image](https://github.com/snezhig/obsidian-front-matter-title/assets/73203026/69beae11-03a2-420b-a318-e10681ec1a9a)

**Comment by snezhig** [comment]
Try to update plugin. [3.6.2](https://github.com/snezhig/obsidian-front-matter-title/releases/tag/3.6.2) fixes.

**Comment by jiajiala** [comment]
![image](https://github.com/snezhig/obsidian-front-matter-title/assets/73203026/d9f19e6a-a3b0-4a4a-8034-0310f4d5a378)
Like above, the file name is "23_0828_200815___Test"

In many parts he is normal as shown as Test

But when displayed in the floating window, it is 23_0828_200815___Test

The Hover window is generated by the Hover Editor

Here are my plugin Settings
![image](https://github.com/snezhig/obsidian-front-matter-title/assets/73203026/b75724d0-227e-41ed-8038-5984b03b45a5)
(\d{2}_\d{2}\d{2}_\d{6})___
![image](https://github.com/snezhig/obsidian-front-matter-title/assets/73203026/8ee7c3db-26a9-4674-aaec-321bb958b0e5)

**Comment by snezhig** [comment]
Do you use a community plugin?
If you want to support this plugin, you can ask the author of the plugin to support my plugin, using [api](https://github.com/snezhig/front-matter-plugin-api-provider)

Example: https://github.com/snezhig/obsidian-front-matter-title/issues/115
