### ISSUE TITLE
Bug: Name becomes hidden when file gets moved to another folder

### ISSUE THREAD

**Issue by pat-richter** [Snezhig/obsidian-front-matter-title#17]
**Steps to reproduce**
- Create a title from front matter
- Move file to another folder in filetree (by drag and drop or hotkey)
- Filename is shown instead of the title from front matter (until Obsidian is restarted)

Thank you very much for this plugin. Your solution works very well!

**Comment by Snezhig** [comment]
Hi, thank you for the feedback.
I will check this and try to fix.

**Comment by Snezhig** [comment]
The [1.4.0 release](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/1.4.0) fixes this error.

**Comment by pat-richter** [comment]
Hi @Snezhig I've downloaded the latest version (and restarted Obsidian). Sadly, the issue has not been fixed for me. 

I'm using the `aliases` entry (tested with and without the new "first entry of list" - feature)

```
---
aliases: 
- "Take this as title"
- 20220615.111026
---
```

**Comment by Snezhig** [comment]
The [1.4.1](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/1.4.1) fixes this bug. I hope.
