### ISSUE TITLE
Mirror-note.

### ISSUE THREAD

**Issue by ivkorolyov** [snezhig/obsidian-front-matter-title#172]
Hello!
I want to make a mirror-note.
Is it possible to use only a part of the string "**Mirror-note**" in a file manager, instead of the entire string "**# ![[2023-09-07_36-4_10-53-42.45#Mirror-note|Mirror-note]]**"?
![image](https://github.com/snezhig/obsidian-front-matter-title/assets/50589503/010d3119-2264-4a2d-b0ae-f6a5f500d07e)
Best regards, thank you.

**Comment by snezhig** [comment]
I do not understand. Sorry.
Why explorer shows this title? What is the settings of plugin?

**Comment by ivkorolyov** [comment]
Your program is working correctly.
I want to suggest a feature.
Ability to create a mirror note, similar to mirror bullets from WorkFlowy. (https://workflowy.com/feature/mirrors/)
To do this, create a heading with a link to the original note.
Еxample: #_[[title_original_note.md#Heading|Heading]]

And the explorer does not take the link but only the Heading.
And it turns out one original note and many mirror notes.
When you change the name of the original note, the names of the mirror notes will also change.

**Comment by ivkorolyov** [comment]
I wanted that for mirror notes, the name would be taken from one common note.
Okay, I can't explain. I do not speak English. Sorry. The topic can be closed.

**Comment by ivkorolyov** [comment]
I want the ability to take a name for a note from another note.

**Comment by ivkorolyov** [comment]
I wrote without thinking. I am sorry.

**Comment by snezhig** [comment]
In my opinion, it is not a part of the plugin idea. It looks like an idea for another plugin which should support my plugin.
My plugin works with templates, it does not parse file to do anything.

The only thing I can suggest is to add a resolver instance inside Processor when it works like a function and you will be able to create any title you want to. You can use regexp to determine if it is a mirror note and use resolver to get an original name.

But I will spend some time thinking about the future.

**Comment by joellti** [comment]
I was looking for similar thing when I ran into this thread. I think the issue can be addressed by making Dataview API (dv object) available to the script in Function of Processor. With that the script will be able to retrieve other notes' information needed to come up with the note title for the current note. It seems the TFile object is already made available to the script in Function so I assume dv object can be added in similar way? Look forward to your comments. Thx
