### ISSUE TITLE
[Feature request] Support Dataview inline fields

### ISSUE THREAD

**Issue by pm64** [snezhig/obsidian-front-matter-title#176]
I'm realizing how convenient it would be for obsidian-front-matter-title to be able to use Dataview inline fields as a title source, perhaps when resolving via frontmatter fails.

https://blacksmithgu.github.io/obsidian-dataview/annotation/add-metadata/

This way, if my template is "alt-title", then as an alternative to having an "alt-title" value in my frontmatter, I can include this somewhere in my note:

alt-title:: My title

Here's the rationale: In terms of the inline title -- one of the great superpowers of this plugin is alleviating the need to include the "desired" title as a header in the document by simply displaying it as the inline title, freeing up vertical screen real estate at the top of the note. This benefit would be maximized if the desired title could be specified in a way that doesn't occupy vertical space at the top of the note.

**Comment by pm64** [comment]
If there's no interest in such a feature, I'll withdraw my request, with sincere gratitude for your consideration. My request is a minor annoyance relative to the huge productivity boost facilitated entirely by this important plugin.

But guys... wouldn't it be great to have your alias defined way at the BOTTOM of the page if you want? Especially since we're sometimes trying to avoid displaying duplicate titles. So we hide a title by... displaying the same title in frontmatter anyway, right at the top of the document? Assuming user has DavaView -- support for a DataView inline field value as an alias source would take my game to a new level of magnitude.

alt-title:: Jello snezhig 

Thanks for all you do!

**Comment by snezhig** [comment]
Sorry, I do not use dataview and I think it is why I did not catch the idea, Could you provide some screenshots to make it more clear for me?

**Comment by pm64** [comment]
@snezhig, I will provide a full illustrated explanation ASAP. Thank you for keeping this open and for your kind patience.

**Comment by pm64** [comment]
Hi @snezhig, was hoping to revisit this request. I'll provide some screen shots to illustrate what I'm proposing.

Currently your plugin refers to specifically to frontmatter (since named "properties") to determine the alternative title.

Typically this appears as follows to the user:

![image](https://github.com/snezhig/obsidian-front-matter-title/assets/10715458/ee1776f3-d262-4517-820f-0ef9a9bd3404)

What I'm proposing is the option to specify the alternative title in a different way.

The current way (depicted above) works great in most cases. But sometimes, displaying the alternative title in the frontmatter could be a distraction, depending on how other properties are being used.

So, I'm proposing support for another syntax that is somewhat ubiquitous in the Obsidian world.. "Dataview inline fields", which use a key:value syntax powered by the Dataview plugin.

See the [Documentation](https://blacksmithgu.github.io/obsidian-dataview/annotation/add-metadata/#inline-fields) for specifics -- but basically, the user could specify the alternative title anywhere in the document (not just in the frontmatter) using the following syntax (on its own line):

```
title:: Frontmatter Title Demo
```

(From the docs: "Note that you need to use a double colon :: between key and value when using inline fields, contrary to YAML Frontmatter fields where one colon is enough")

The advantage of using this option is that the alternative title could then appear at the end of the document, if the user desired.

That way, it's handled more "in the background", and can be less of a distraction, if this is the user's preference.

Hope this better explains the request, let me know if I can provide more info or you want to discuss. Thanks for your consideration.

**Comment by a13ph** [comment]
as a workaround, you can hide title metadata field in Properties, using Metadata Hider plugin

**Comment by pm64** [comment]
Thanks @a13ph, that could be a good workaround for some users, though it has the side-effect of also hiding every property with empty value.

**Comment by a13ph** [comment]
> Thanks @a13ph, that could be a good workaround for some users, though it has the side-effect of also hiding every property with empty value.

I agree, I could use such an option there. I've added a feature request to make that optiional.
https://github.com/Benature/obsidian-metadata-hider/issues/5

**Comment by Benature** [comment]
> > Thanks @a13ph, that could be a good workaround for some users, though it has the side-effect of also hiding every property with empty value.
> 
> I agree, I could use such an option there. I've added a feature request to make that optional. [Benature/obsidian-metadata-hider#5](https://github.com/Benature/obsidian-metadata-hider/issues/5)

Hiding every property with empty value can be disabled in the settings with v.0.1.3 now :)

**Comment by pm64** [comment]
Indeed @Benature, recent enhancements to https://github.com/Benature/obsidian-metadata-hider render this FR moot! And I can close this issue on that basis.

Thank @a13ph and @Benature for your help on this.
