### ISSUE TITLE
Read emoji value from `icon:` in front matter to prepend to title

### ISSUE THREAD

**Issue by redactedscribe** [snezhig/obsidian-front-matter-title#182]
I've recently been using a plugin named [Iconize](https://github.com/FlorianWoelki/obsidian-iconize) to be able to display emoji next to inline titles. Before this, I was using Front Matter Title (FMT) to achieve this by duplicating the file's name as its `title:` value, but also prepending an emoji to it, e.g. `title: 🙂 Hello`. This was good but the downside was having to manage both the file name and `title:` separately. Iconize doesn't have this issue because the emoji has its own key.

With Iconize, we can define an emoji (but also SVG icons) in `icon:` and the plugin will add it to filenames in the sidebar, and optionally above the inline title and/or in the file's tab. So I can achieve a similar effect to what I was achieving with FMT, but icons won't show up in all other UI areas -- which there are many and which FMT supports. I think it would make little sense for Iconize to implement all of this when FMT already does this so well, so the simplest solution to me would be for FMT to implement reading `icon:` values. Iconize lets you define a emoji, or strings which relate to names of SVGs from its icon packs, but FMT would only support `icon:` if its value was an emoji.

How I see this working is this:

- If `icon:` has a value, prepend the emoji to all titles which have been enabled in FMT's options. The `title:` could be empty and the emoji should still be displayed.
- If `icon:` and `title:` have values, rewrite all enabled titles like normal, but with the `icon:` value prepended before them.

Using the `icon:` key for displaying an emoji in the title isn't quite a standard, but I know Iconize and the software Logseq can do so, and I believe others too. By supporting `icon:`, this would mean FMT and Iconize could play nicely together, e.g. use SVGs for folder names if you so choose, and use the 'icon:`  value via FMT for the graph, bookmarks, etc.

This FR strays slightly outside of the do-one-thing-only-and-do-it-well philosophy, however title icons are closely related, or even consider part of, titles and could be a suitable (and very welcome) addition to FMT if supported.

Thanks!

Just for reference, FMT supports modifying titles in these parts of the UI:

![Obsidian_2023-11-01_16-14-54](https://github.com/snezhig/obsidian-front-matter-title/assets/25013746/d6e4c5fc-48bb-4262-a158-f90caea0763b)

**Comment by snezhig** [comment]
Hi.
Did you try to combine "text part" of title and "icon part" using composite templates?
Like "{{icon}} {{title}}"?  Or you want to have an option just to prepend an icon without rewriting?
Just imagine if FMT could provide you an  option to set the template like "{{icon}} {{title|original}}" and plugin rewrites shown titles using icon + (title value or original name)? 
I think that this behavior can be reached by using Processor in settings.

**Comment by redactedscribe** [comment]
> Did you try to combine "text part" of title and "icon part" using composite templates?
Like "{{icon}} {{title}}"? Or you want to have an option just to prepend an icon without rewriting?

I don't think so. I only did a crude `title: <icon> <title>` to achieve the result.

> Just imagine if FMT could provide you an option to set the template like "{{icon}} {{title|original}}" and plugin rewrites shown titles using icon + (title value or original name)?
I think that this behavior can be reached by using Processor in settings.

This sounds like a nice idea. This means a rewrite will _always_ happen, even if `title:` is empty. Maybe this is a performance problem for big vaults e.g. in the graph? I don't know. There may be some other benefit to having the icon managed separately of rewriting, but you would know this better than me.

Some thoughts:

- Instead of specifically supporting `icon:` from the front matter, maybe support reading _any_ front matter value and using that in the rewritten title? This would let us use `{{icon}} {{title|original}}`, or e.g. `{{date}}: {{title}}`. FMT probably shouldn't care what the value is, just insert it into the rewrite step.
- What happens when `icon:` has no value and `{{icon}} {{title}}` is specified? Will we end up with "{space}<title>"? What about `{{icon}} {{other}} {{title}}` and `other:` doesn't exist? Will we get "<icon>{space}{space}<title>"? How do we suppress unwanted whitespace? Some programs allow e.g. `{{icon }}` (with space) and if `icon:` is empty, the space is not inserted.

**Comment by snezhig** [comment]
The excess whitespace problem does not seem like something difficult. I think that template "{icon }{title|another_field}" lets you realize your idea and will work like:
* ((value from "icon" + space) **or** nothing) **plus** (value from "title" **or** value from "another_field" **or** nothing)

**Comment by snezhig** [comment]
3.7.0 version supports logic with spaces and conditional keys like "title|another_key".
https://github.com/snezhig/obsidian-front-matter-title/blob/master/docs/TemplateExamples.md#logic

**Comment by redactedscribe** [comment]
Thank you @snezhig!

In my case, using `{{icon }}{{title|_basename}}` for the Common main template value achieves my goal. It works in all UIs, except for #104 (but this is known).
