### ISSUE TITLE
Renaming a note renames it based on its template title instead of its basename

### ISSUE THREAD

**Issue by redactedscribe** [snezhig/obsidian-front-matter-title#185]
For example:

1. Common main template value `{{icon }}{{title|_basename}}` and processor disabled.
2. Create new file Test and add `icon: 🙂` front matter.
3. In Files tab, you see "🙂 Test".
4. Renaming the file via the sidebar shows "🙂 Test" as the value which can be edited, instead of "Test".
5. Just press enter (or click away) and the file's basename is now "🙂 Test" and displays as "🙂🙂 Test" in the file's inline title (but only shows "🙂 Test" in the Files tab for some reason).

If **Settings > Files & Links > Automatically update internal links** is enabled then all "[[Test]]" wikilinks are now modified to be "[[🙂 Test]]" instead.

**Comment by snezhig** [comment]
In 3.7.1 plugin should set basename when file is being renamed.

**Comment by redactedscribe** [comment]
It works, thank you.
