### ISSUE TITLE
[Feature Request] Option to view real name

### ISSUE THREAD

**Issue by gentlegiantJGC** [Snezhig/obsidian-front-matter-title#19]
It would be useful to be able to see if the name displayed is the real name or the title.

I found this plugin before finding yours that does something similar but also shows the real name next to the title.
https://github.com/hodlen/obsidian-md-title-sidecar
Example of what I am referring to
https://github.com/hodlen/obsidian-md-title-sidecar/blob/main/images/Sidebar.png
I tried using this but it seems to have quite a few bugs.

**Comment by Snezhig** [comment]
I had the similar idea and I think that It can be possible by addition reserved template like `{{original_name}}`.

**Comment by Snezhig** [comment]
You can try [1.5.0-beta release](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/1.5.0-beta)
It brings something similar you want to.

**Comment by Snezhig** [comment]
I am going to close this issue. Feel free to open it again or create new if something is wrong.
