### ISSUE TITLE
"alias" property has been deprecated

### ISSUE THREAD

**Issue by memex-social** [snezhig/obsidian-front-matter-title#191]
The "alias" property has been deprecated since 1.4.5.

https://obsidian.md/changelog/2023-08-31-desktop-v1.4.5/

> About tag/alias/cssclass properties
> As of 1.4.0, we have deprecated the "tag", "alias", and "cssClass" properties. 
 properties to tags, aliases, and cssclasses and the values will automatically be converted to lists.
>
> The old property names will still be identified correctly in the app, but the property editor will always prefer tags, cssClasses, and aliases.

However, the plugin prioritises the 'alias' property to modify the cache of aliases. Therefore, when browsing the Properties View, there is always the 'alias' property that cannot be merged into aliases.

We suspect that this is probably caused by the following code.

https://github.com/snezhig/obsidian-front-matter-title/blob/2cbf1b135d217eeb92ec337a13ef4d81f777c4ae/src/Feature/Alias/Alias.ts#L11

**Comment by snezhig** [comment]
Fixed in 3.8.2

**Comment by memex-social** [comment]
Thank you for fixing it! I have confirmed that this isssue has been resolved and will close.
