### ISSUE TITLE
Disabling Core Plugin "Files" causes an error

### ISSUE THREAD

**Issue by memex-social** [snezhig/obsidian-front-matter-title#192]
Disabling the File Explorer Plugin and enabling the Explorer feature causes an error and stops this plugin.

**Comment by snezhig** [comment]
Hi. Do you mean that another plugin affects on my plugin?

**Comment by memex-social** [comment]
Sorry." File Explorer" is a misspelling of the Core Plugin "Files".
The following are the details of the error.

［Steps to reproduce］

1. enable the "Files" Feature in the settings of this plugin.
2. disable the Files Plugin
3. open any Markdown file


[Expected Behavior]

Other enabled features such as Backlinks and Inline Title work fine and the title is displayed.

[Actual Behavior]

1.  the title is not displayed at any position
2. the following error message appears in the Developer Console

> Uncaught (in promise) Error: Explorer view is undefined
>    at ExplorerManager.getExplorerView (plugin:obsidian-front-matter-title-plugin:7614:13)
>    at ExplorerManager.doEnable (plugin:obsidian-front-matter-title-plugin:7604:30)
>   at ExplorerManager.enable (plugin:obsidian-front-matter-title-plugin:7555:31)
>    at FeatureComposer.toggle (plugin:obsidian-front-matter-title-plugin:7684:42)
>    at FeatureComposer.toggle (plugin:obsidian-front-matter-title-plugin:7682:19)
>    at MetaTitlePlugin.reloadFeatures (plugin:obsidian-front-matter-title-plugin:11249:15)
>    at eval (plugin:obsidian-front-matter-title-plugin:11231:12)
>    at t.onLayoutReady (app.js:1:1976216)
>    at MetaTitlePlugin.bind (plugin:obsidian-front-matter-title-plugin:11224:24)
>    at MetaTitlePlugin.onload (plugin:obsidian-front-matter-title-plugin:11190:10)

**Comment by snezhig** [comment]
I will check it.

**Comment by snezhig** [comment]
Check 3.8.2, version. Should be fixed.

**Comment by memex-social** [comment]
Thank you for fixing it! I have confirmed that this isssue has been resolved and will close.
