### ISSUE TITLE
Focus note title (filename) after note creation

### ISSUE THREAD

**Issue by redactedscribe** [snezhig/obsidian-front-matter-title#193]
Currently after creating a note, the inline title / tab title bar doesn't have its text preselected so that it can be immediately renamed (default Obsidian behaviour). After note creation, it looks like the focus is in the inline title for me, but I cannot type or see a cursor. I presume this because pressing tab makes the cursor appear in the blank note's body.

Ideally the title should be preselected even if the file was created via other means, such as another plugin. Maybe the fix is a matter of _not_ doing something (so that Obsidian's default behaviour occurs)?

It's possible that this a conflict with another plugin as I did not test this entirely in isolation, but it does appear that FMT is the culprit because disabling FMT resolves the problem.

Thanks.

**Comment by snezhig** [comment]
Hi. If plugin works correctly without another plugin, it means that another plugin do something that breaks plugin behavior. I have just clicked on "New note" icon and title was preselected.  How exactly do you create a new notes? They are empty or no by default? What plugin do you use?

**Comment by redactedscribe** [comment]
Hello @snezhig,

I disabled 3 plugins then tested FMT plugin. I repeated this until there were 0 other plugins, only FMT. Then I restarted Obsidian and tried again with only FMT enabled and the bug is still occurs. I disabled FMT so that 0 plugins are enabled and created a note: The inline title is preselected.

My testing was done using Ctrl+P + "new note". I think there is no difference between this and the new note button. [Another plugin](https://github.com/Lisandra-dev/obsidian-create-note-in-folder/releases) had this inline title highlight issue too and they made a fix in a recent release, but when FMT is enabled, the fix does not work. Hopefully any fix you make will not conflict.

My FMT settings:

Main: `{{icon }}({{title}})({{_basename}})`
Fallback: `_basename`
Features' template: none

Processor:

```js
// Source: https://github.com/snezhig/obsidian-front-matter-title/issues/179#issuecomment-1793429778
var {
    groups: {
        icon,
        t,
        basename
    },
} = title.match(new RegExp(`(?<icon>.*)\\((?<t>.*)\\)\\((?<basename>.*)\\)`));
return `${icon}${t? t+ " *" : basename}`
```

Features:
![Obsidian_2023-12-05_22-37-16](https://github.com/snezhig/obsidian-front-matter-title/assets/25013746/5f212161-2315-4faf-836c-9a30b6063821)

I tried once with Processor disabled, but it didn't help.

**Comment by snezhig** [comment]
I will check it soon.

**Comment by snezhig** [comment]
Check 3.8.2, version. Should be fixed.

**Comment by redactedscribe** [comment]
Thank you. The situation has improved I think, but there is still one case where the title is not selected: When creating notes using the other plugin I mentioned: [Create Note in Folder](https://github.com/Lisandra-dev/obsidian-create-note-in-folder).

With both plugins enabled (+ Templater), the inline title is selected when creating a note via all methods except when created via Create Note in Folder plugin. If I disable FMT, then the title is gets selected using the same method. It seems there is an incompatibility between FMT and Create Note in Folder. It would be really great if they could work together because I exclusively create notes via this plugin. Maybe you can have a look?

**Comment by snezhig** [comment]
I have tried, but I the only thing I can do is to focus inner title without selection all title.
The best solution as I think is to change logic in "Create Note in Folder" plugin.
It has the following function:
```js
async function focusInlineTitle(leaf: WorkspaceLeaf | undefined) {
	if (!leaf) {
		return;
	}
	const titleContainerEl = leaf.view.containerEl.querySelector("div.inline-title");
	if (!titleContainerEl) {
		return;
	}
	// @ts-ignore
	await titleContainerEl.focus();
	window.getSelection()?.selectAllChildren(titleContainerEl);
	return;
}
```
After `await titleContainerEl.focus();` the plugin can repeat  `leaf.view.containerEl.querySelector("div.inline-title");` to can actual element and call selection.

**Comment by Lisandra-dev** [comment]
Sorry, I tried to do that:
```ts
async function focusInlineTitle(leaf: WorkspaceLeaf | undefined) {
	if (!leaf) {
		return;
	}
	const titleContainerEl = leaf.view.containerEl.querySelector("div.inline-title");
	if (!titleContainerEl) {
		return;
	}
	// @ts-ignore
	await titleContainerEl.focus();
	const innerTitle = leaf.view.containerEl.querySelector("div.inline-title");
	if (innerTitle) {
		// @ts-ignore
		innerTitle.focus();
		window.getSelection()?.selectAllChildren(innerTitle);
	}
	else window.getSelection()?.selectAllChildren(titleContainerEl);
	return;
}
```
But it doesn't works :/
Do you have an idea ? I think I misunderstood what you said about the way I need to edit that.

**Comment by snezhig** [comment]
@Lisandra-dev thank you. I will check it and hope that we will find the solution.

**Comment by snezhig** [comment]
@Lisandra-dev there is the simplest way:
```js
	if (!leaf) {
		return;
	}
	let titleContainerEl = leaf.view.containerEl.querySelector("div.inline-title");
	console.log(titleContainerEl)
	//scroll to top
	if (!titleContainerEl) {
		return;
	}
	await titleContainerEl.focus();
	//Find again and filter
	titleContainerEl = Array.from(leaf.view.containerEl.querySelectorAll("div.inline-title"))
		.filter(e => !e.hidden).first();
	window.getSelection()?.selectAllChildren(titleContainerEl);
```
I will update my plugin to support focus action on fake element.

**Comment by Lisandra-dev** [comment]
Thanks!

**Comment by snezhig** [comment]
I close this issue. If it's actual, feel free to reopen.
