### ISSUE TITLE
Incorrect comma handling

### ISSUE THREAD

**Issue by ChenghaoMou** [snezhig/obsidian-front-matter-title#199]
First, thank you so much for this plugin!

The issue can be replicated using the following snippet:

```
---
aliases: ["Test, Sample"]
title: "This is a test"
---

[[This is a test|]]
```

With the `Alias` feature turned on
<img width="306" alt="SCR-20231226-nswd" src="https://github.com/snezhig/obsidian-front-matter-title/assets/32014649/50563635-fc68-476a-ad78-440ec168fe6c">

Without this plugin or "Alias" feature turned on:

<img width="325" alt="image" src="https://github.com/snezhig/obsidian-front-matter-title/assets/32014649/f52d263e-7c8f-4b0e-a095-7ac9b22a4030">

Obsidian has changed its non-standard YAML grammar due to [the same issue](https://forum.obsidian.md/t/yaml-entry-with-commas-within-quotation-marks-should-produce-a-single-entry/19046).

**Comment by snezhig** [comment]
Is this issue relevant?

**Comment by ChenghaoMou** [comment]
I can still reproduce the issue with Alias enabled:
<img width="732" alt="image" src="https://github.com/snezhig/obsidian-front-matter-title/assets/32014649/a403b341-a087-466e-a393-afca1f0cbe28">

This is triggered when you type `|`.

**Comment by snezhig** [comment]
![изображение](https://github.com/snezhig/obsidian-front-matter-title/assets/3987716/797c26fe-5d09-418b-aa4b-2b7e0c21b53c)

**Comment by ChenghaoMou** [comment]
I reinstalled the plugin and now it works as expected. Will close this issue, and thank you for your time.
