### ISSUE TITLE
Errors displayed when I enable the plugin

### ISSUE THREAD

**Issue by gmclelland** [snezhig/obsidian-front-matter-title#200]
Hello, thank you for making this plugin.

Recently, after upgrading to the most recent version, I noticed some errors that were displayed.

![Screenshot](https://github.com/snezhig/obsidian-front-matter-title/assets/40570/01b46550-7976-4c4b-8db9-8cebc5d42659)

These errors show anytime I start Obsidian on all of my devices laptop or mobile and when I disable/enable this plugin.

Thought you might want to know.  Let me know if you need anymore details.

**Comment by snezhig** [comment]
@gmclelland can you give me your settings of plugin and output from console?

**Comment by gmclelland** [comment]
I don't think I've changed the settings at all yet?

I didn't see much output from the console when I had a note opened and toggled the plugin off/on:

![CleanShot 2023-12-29 at 12 25 23](https://github.com/snezhig/obsidian-front-matter-title/assets/40570/7f27014c-437e-429e-b9db-1f3392557654)

Though when I visited the plugin's settings screen, it did show this:

![CleanShot 2023-12-29 at 12 29 43](https://github.com/snezhig/obsidian-front-matter-title/assets/40570/e99ba181-87e8-4ec8-bac8-fe0a72ce7fb7)

```
plugin:obsidian-front-matter-title-plugin:9584

Uncaught TypeError: this.item.get is not a function
    at eval (plugin:obsidian-front-matter-title-plugin:9584:89)
    at e.addText (app.js:1:1432940)
    at TemplatesBuilder.buildTemplate (plugin:obsidian-front-matter-title-plugin:9581:156)
    at TemplatesBuilder.doBuild (plugin:obsidian-front-matter-title-plugin:9569:10)
    at TemplatesBuilder.build (plugin:obsidian-front-matter-title-plugin:9550:10)
    at SettingsTab.display (plugin:obsidian-front-matter-title-plugin:7127:19)
    at t.display (plugin:obsidian-front-matter-title-plugin:7103:36)
    at t.openTab (app.js:1:2741344)
    at t.openTabById (app.js:1:2741926)
    at app.js:1:2712527
```

Maybe that helps?

**Comment by snezhig** [comment]
Wow, can you give me a content of plugin settings?
<your_vault_path>/.obsidian/plugins/obsidian-front-matter-title-plugin/data.json

**Comment by gmclelland** [comment]
Here you go:

[data.json](https://github.com/snezhig/obsidian-front-matter-title/files/13799552/data.json)

**Comment by snezhig** [comment]
@gmclelland It's old settings version. Very old. A have added new migration for 3.8.3 version. Update plugin please.

**Comment by gmclelland** [comment]
Thanks snezhig!  That fixed the problem.  I see all the new settings now.
