### ISSUE TITLE
[Feature request]: add support for rules based of folders or even arbitrary logic

### ISSUE THREAD

**Issue by Lyzod** [snezhig/obsidian-front-matter-title#211]
I hope it's not too much to ask, but I would like to use different rules for different parts of my vaults. 

In one part of my vault, I use front matter titles, in the other I use headings as the title, but in both, frontmatter title and headings exist. 

I think the current logic doesn't allow me to make this check eg if a title is contained within a certain folder. 

It would be great and if some people have different needs (special titles containing XY), if I could feed it an instructive file, that contains the rules based of checks. 

Eg. 

if file is in folder A, then title= heading

if file name contains "Example String", then title is frontmatter value

etc

Thank you very much for your work.

**Comment by snezhig** [comment]
Now you can try to use a processor, but it will be a long function with many conditions. Also it requires javascript knowledge to write it. 
An option I can suggest is let you define your own function that will return a template for plugin depending on file, but it still requires JS knowledge.

**Comment by Lyzod** [comment]
That's not the biggest issue. Can you point me to your processors documentation, so I can work out how to do it?

**Comment by snezhig** [comment]
Here: [Doc](https://github.com/snezhig/obsidian-front-matter-title/blob/master/docs/Processor.md)

You can use it using following logic:
 - Create a template like: `{{#heading}} {{title}} {{_basename}}/{{_path}}`
 - You will get a title like this: `My Heading My Title path/to/file`
 - Using a regexp split string and return only part you want to

**Comment by Lyzod** [comment]
Thank you very much. I guess I need to deepen my JavaScript knowledge for that and I will probably do it. Thanks!
