### ISSUE TITLE
[Feature request]: Add option to display 2 titles at once 

### ISSUE THREAD

**Issue by Lyzod** [snezhig/obsidian-front-matter-title#212]
The original "file-explorer-markdown-titles" which is now defunct I think has the option (i think) to display the second titles kinda like an alias below the original title. It would be nice if one could choose to display to titles, similar to how Zettlr shows both the UUID and the chosen note title.

**Comment by snezhig** [comment]
You can use complex title, to show original filename.
![изображение](https://github.com/snezhig/obsidian-front-matter-title/assets/3987716/98f84d67-0cd8-48d8-a2b9-f391a5a64e26)

**Comment by Lyzod** [comment]
That's a good solution. I haven't thought about that! 

It doesn't do the nice visual cue with the linebreak and the different formatting, but still great
