### ISSUE TITLE
change the plugins name to reflect its whole abilities and scope 

### ISSUE THREAD

**Issue by Lyzod** [snezhig/obsidian-front-matter-title#213]
I had troubles finding/ considering this plugin for my use case as the name implies that it only accepts frontmatter titles. 

I think that this plugin has grown so much that this doesn't reflect what it does anymore. Custom templates, headings, granular control in various places of the app... This is so much more. 

I would suggest the name "Obsidian custom title" as this encompasses the whole scope of it.

**Comment by snezhig** [comment]
I thought about this, yes.

**Comment by snezhig** [comment]
Created a discussion: https://github.com/snezhig/obsidian-front-matter-title/discussions/214
