### ISSUE TITLE
Search for files in WikiLink by set title

### ISSUE THREAD

**Issue by ekarious** [snezhig/obsidian-front-matter-title#217]
One thing I notice is when I create a new WikiLink `[[]]` and I write a few letters/words, it search the files by filename and not by the title set in the plugin. So, in the case of a Zettelkasten, I need to put the ID of note instead which is not great.

Is it possible to change that behavior with the plugin itself ? Or Obsidian needs to be updated ?

**Comment by snezhig** [comment]
Hi.
My plugin does not search anything. It just replaces the shown text.
But you can use [Alias Feature](https://github.com/snezhig/obsidian-front-matter-title/blob/master/docs/Features.md#alias) to add the title in alias properties. Obsidian searches files by aliases.

**Comment by ekarious** [comment]
Thank you. I'll try that.
