### ISSUE TITLE
Add support for title from H1-only

### ISSUE THREAD

**Issue by galligan** [snezhig/obsidian-front-matter-title#219]
I like the flexibility of using headings or title properties, but am finding myself wanting the heading feature to be a little more focused.

Specifically, I only want it to use the H1 (`# Heading`) or else I want it to use the fallback `title` in the properties.

**Comment by snezhig** [comment]
Sorry, but I did not get the idea. Can you give me an example?

**Comment by galligan** [comment]
@snezhig when trying to work through an example, I realized that I was mistaken and the `#heading` template format does indeed serve my needs. Closing issue.

**Comment by galligan** [comment]
@snezhig funny, but re-opening this as I finally figured out what I was looking for.

I would like to use `#h1` as distinct from `#heading`. Here's an example to show why. We'll call this file `MyNote.md`:

Example 1 (with H1)

```md
---
title: My Title
---

# My H1 Title

## Overview

Here's some content

## Conclusion

```

Example 2 (without H1)

```md
---
title: My Title
---

## Overview

Here's some content

## Conclusion

```

Example 3 (without H1 or title)

```md
## Overview

Here's some content

## Conclusion

```

In the above example, let's say I'm using `#heading|title|_basename` as the common main template, then resulting titles would be:

- Example 1: `My H1 Title`
- Example 2: `My Title`
- Example 3: `Overview`

Obviously `Overview` is less than ideal, and probably not as good as what the `_basename` might have been.

Now, if the same used `#h1|title|_basename` instead, we'd get:

- Example 1: `My H1 Title`
- Example 2: `My Title`
- Example 3: `MyNote`

This is essentially what I'm going for. I typically reserve H1's for titles (as is markdown-lint standards), and H2's for sometimes generic headings. That's where `#heading` falls short as-is. In most cases, the frontmatter `title` and filename would be more useful than the first `## Heading` which may be generic.

---

I had a good laugh finding this, because I was trying to do the exact same thing over again, this time thinking about `#h1` without realizing I'd looked for the same thing before. Then when I searched issues, I found one! And it was my own damn issue, closed because I couldn't figure out at the time how to say what I meant. 🤣

**Comment by snezhig** [comment]
Front Matter Title is being maintained again and a new version is out. The old issue/PR backlog has been reviewed against current Obsidian (1.12.7) and is being closed; all open PRs are closed too. The reports and ideas are kept in the maintenance plan.

If this still affects you on the latest version, or you have a feature request, please open a new issue with a short description (and repro steps + versions for bugs). Thanks!
