### ISSUE TITLE
Bug in Quick Switch Dialog caused from comma

### ISSUE THREAD

**Issue by pat-richter** [Snezhig/obsidian-front-matter-title#22]
The quick switch dialog doesn't show the full title, when it contains a comma. I've created a video to show the behaviour: https://drive.google.com/file/d/1ZTzypNW6sbT_LjxiCEHAqy-OqffmHJW6/view?usp=sharing

It works if I use the new "first entry of list" feature.

Thank you very much!

**Comment by Snezhig** [comment]
This plugin does nothing with "Switch dialog", so It's obsidian's behavior. I reproduces this without the plugin.
