### ISSUE TITLE
Is it possible to start it lazy?

### ISSUE THREAD

**Issue by MrModest** [snezhig/obsidian-front-matter-title#237]
Obsidian's launch time analyzer shows that the plugin takes more than a second of the app launching time.
Is it possible not to block the app's start and do all title replacement in the background thread?

Here's the result of "Startup time"
```
Obsidian start-up time breakdown

Obsidian version: v1.7.7
Installer version: v1.4.16
Operating system: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103 23.4.0

- Total startup time: 1,860ms
- Initialization: 503ms
- Vault (255 files): 48ms
- Workspace (10 tabs, 8 deferred): 92ms
- Core plugins: 29ms
- Community plugins (9 active): 1,189ms
  - Front Matter Title (v3.12.0): 1,021ms
  - Git (v2.30.1): 58ms
  - DataLoom (v8.16.1): 52ms
  - Dataview (v0.5.67): 32ms
  - LanguageTool Integration (v0.3.7): 8ms
  - Editing Toolbar (v2.4.16): 8ms
  - Tag Wrangler (v0.6.1): 4ms
  - Sortable (v0.3.1): 1ms
  - Underline (v1.3.0): 1ms
 ```

You can find the analyzer in the "General" tab, under the "Advanced" section, when you click on the "stopwatch" icon.
<img width="821" alt="image" src="https://github.com/user-attachments/assets/55e665b7-c92e-4194-bcaa-42a49ec21915">

**Comment by MrModest** [comment]
https://github.com/user-attachments/assets/259eb5b2-f500-4bf7-a793-e1330d020adb

**Comment by snezhig** [comment]
@MrModest you can set delay as 0.
![изображение](https://github.com/user-attachments/assets/6ef5e902-01b1-4564-b4ae-54b02f4139e6)

С последними обновлениями видимо само приложение стало ожидать полного завершения асинхронной загрузки, я добавлю опцию отложенной загрузки в фоне.

**Comment by snezhig** [comment]
Now you can see loading time with new "background" option.
![изображение](https://github.com/user-attachments/assets/c0afe069-cc36-4854-b8e1-a4579f02bfa6)
![изображение](https://github.com/user-attachments/assets/d92e648d-8092-4ea7-a92f-a3567aa69a78)

**Comment by MrModest** [comment]
Works perfectly with the default settings, thank you! 
<img width="469" alt="image" src="https://github.com/user-attachments/assets/37423fe1-7d05-4ef1-ba3b-78a34da36ee9">
