### ISSUE TITLE
Dataview variables break file rename

### ISSUE THREAD

**Issue by Exomancer** [Snezhig/obsidian-front-matter-title#24]
I have a file with two dataview variables in the YMAL frontmatter.  The file retained it's 12 digit Zettelkasten file name and would not display the file name from the YMAL front matter variable.  When I moved the Dataview variables out of the YMAL section, the plugin worked and renamed the file as it was supposed to do.  The Dataview variables have nothing to do with this plugin that I can see and are not even close as far as variable names.  They were there to create a date in the document.

Installed plugin version 1.4.1
Obsidian 1.2.2 (56) API 0.14.15 (Android)

**Comment by Snezhig** [comment]
Hi! 

Could you add any examples, screenshots or a record? I'm not sure that I understand what `dataview variable` means.

Thank you for the feedback.

**Comment by Exomancer** [comment]
The YMAL is:

```
---
filename: Obsidian Dataview Date Math
tags:
doy:: `=dateformat(date(today), "ooo")`
dsvg:: `=3760/365`
---
```

The "filename" variable is to rename the document
The "doy" and "dsvg" are the dataview variables.  With them inside the YMAL as above, the filename will not be used by your plugin.

If I move them outside the YMAL your plugin works.

I also noticed that if I use an alias like so:

```
---
filename: Obsidian Dataview Date Math
alias: [Obsidian Dataview Date Math]
---
```

and forget one of the brackets like so:

```
---
filename: Obsidian Dataview Date Math
alias: [Obsidian Dataview Date Math
---
```

the filename will not be renamed.

**Comment by Snezhig** [comment]
Thank you for the examples.
I guess that Obsidian does not return a valid fronmatter because it can not parse your yaml section. It seems broken. But I will check it and give you the answer.

**Comment by Snezhig** [comment]
Yes, I checked this and Obsidian's MetaDataCache just does not contains frontmatter key for files with your examples of yaml section.
But I will look at option to have a possibility to get the data in another way.

**Comment by Exomancer** [comment]
It could be me.  I'm new to Databiew and that looked like how the variables are put in.  I could be wrong/  However I just think it's a point that something in the YMAL broke the ability of your plugin to rename the files.

**Comment by Snezhig** [comment]
You can try this to valid your yaml: http://www.yamllint.com/
If yaml is not correct, obsidian does not cache it and my plugin have nothing to work with.

**Comment by Exomancer** [comment]
Thank you.  The backticks in the Dataview variables was making the YMAL invalid.  I got that syntax from a post on Databiew.

**Comment by Snezhig** [comment]
So can we close this issue or you have some questions?

**Comment by Exomancer** [comment]
Well I assume alias syntax errors do the same thing so yes you can close the issue.
