### ISSUE TITLE
BUG: It doesn't work about the button.

### ISSUE THREAD

**Issue by YIRU69** [Snezhig/obsidian-front-matter-title#27]
The button always on. I try to push it off, but it doesn't work. Why?
![image](https://user-images.githubusercontent.com/48148292/175771016-4926de2b-48e1-4088-ae87-732f39f46080.png)

**Comment by Snezhig** [comment]
Hello.
What is your version and what is the theme? I do not have such problem. Can you give me more info and screen record?

**Comment by YIRU69** [comment]
@Snezhig obsidian-v 0.14.15  plugin-v 0.15
theme: shimmering focus
![1](https://user-images.githubusercontent.com/48148292/175778740-297f8129-7c18-4033-97eb-593ab43877c7.gif)

**Comment by Snezhig** [comment]
Yea, I got the bug.
Try to update to [1.5.1](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/1.5.1)

**Comment by Snezhig** [comment]
@YIRU69 have you tried new release? Bug is solved?

**Comment by YIRU69** [comment]
@Snezhig  Thank you very much. I will close the issue.
