### ISSUE TITLE
[FEATURE] Option to actually rename files to 'title'

### ISSUE THREAD

**Issue by archont00** [Snezhig/obsidian-front-matter-title#28]
While Obsidian is my main note taking app, I also view/edit my markdown files with other software (like MarkDown Editor in Nextcloud).

So, it would be quite helpful if this plugin could also rename the file to match the frontmatter title (with some transliteration of illegal characters and max length).

**Comment by Snezhig** [comment]
Hi. This is a dangerous feature, but possible.

**Comment by archont00** [comment]
That certainly is.

Another alternative would be to set front matter title the same as the actual filename - yes, some chars could not be used in title, but that is an acceptable drawback to reaching the objective: having the file name and title metadata the same and providing some level of compatibility across MD viewers/editor.

**Comment by Trikzon** [comment]
Out of curiosity, what use do you have in having the file name and title metadata be the same? Isn't the point of this plugin to be able to have them be different?

**Comment by Snezhig** [comment]
Yes. The main idea of this plugin is to provide possibility to keep any original name, but see another.
This plugin is not about having affect on files for now, but some little features might appear in the future.

**Comment by archont00** [comment]
Actually, there is already a community plugin https://github.com/dvcrn/obsidian-filename-heading-sync which fits my use case well. Closing the feature request now.
