### ISSUE TITLE
Console error if title property is missing

### ISSUE THREAD

**Issue by huyz** [Snezhig/obsidian-front-matter-title#30]
This has no impact but there's an error in the dev console if there is no `title` property in the frontmatter:

![screenshot 2022-06-30T085705Z](https://user-images.githubusercontent.com/128394/176636550-eddd2ad1-0ba6-40df-a870-4105d8be4590.png)

**Comment by Snezhig** [comment]
Hello. I will check this. Thank you for the feedback.

**Comment by huyz** [comment]
Hmm can't repro anymore.
