### ISSUE TITLE
[Feature Request] Add whitelist functionality

### ISSUE THREAD

**Issue by marvin-te** [Snezhig/obsidian-front-matter-title#32]
Hi there. 
I really like your plugin and use it for my Zettelkasten note taking system as there the files have ids in their name, which are not pleasent in the file tree and graph view.
For that I use the `aliases` property, so I can use the titles to link to the notes.

But sometimes I use the aliases property in other notes, where I do not want them to be "renamed".
Could you please add a feature, so one can choose that _only certain notes_ will be affected by your plugin? Since you already have an exclude functionality for folders, I think it shouldn't be too hard to implement the same functionality in reverse.

Thank you very much.
Cheers.

**Comment by Snezhig** [comment]
Hello. Yea, I think it is possible to realize white list feature.

**Comment by Snezhig** [comment]
@marvin-te 
Hi, you can try [ beta version 2.0.0](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/2.0.0-beta), using [BRAT](https://github.com/TfTHacker/obsidian42-brat). Read this [readme](https://github.com/Snezhig/obsidian-front-matter-title/tree/dev).
It brings whitelist mode.

**Comment by Snezhig** [comment]
@marvin-te  here is [2.0.0 release](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/2.0.0).
