### ISSUE TITLE
[Feature Request] Add first line key

### ISSUE THREAD

**Issue by justl00kingfor** [Snezhig/obsidian-front-matter-title#33]
Hi,

Could you consider to add a special key which returns the content of first non empty line after metablock?

Thanks.

**Comment by justl00kingfor** [comment]
I would like to use the first line of content of a note (after metadata block) as meta title. 

If my note is like this:

>>>>
---
id: 220710140811
aliases: [220710140811]
tags: [untagged]
---

This is my first line of content 

another line 

more one line

<<<<

the special key "_firstline" will return "This is my first line of content" as meta title for my note

would be great if you can strip out some prefixes like headers, lists, … (#, -, 1., …):

# This is my first line of content  -> This is my first line of content 

- This is my first line of content  -> This is my first line of content 

1. This is my first line of content  -> This is my first line of content 


maybe it'll be necessary to return only allowed characters. I don't know it.

**Comment by Snezhig** [comment]
@justl00kingfor Hi, you can try [ beta version 2.0.0](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/2.0.0-beta), using [BRAT](https://github.com/TfTHacker/obsidian42-brat). Read this [readme](https://github.com/Snezhig/obsidian-front-matter-title/tree/dev).
It brings heading support.

**Comment by Snezhig** [comment]
@justl00kingfor here is [2.0.0 release](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/2.0.0).

**Comment by justl00kingfor** [comment]
@Snezhig Great! I couldn't play with it yet, but I will do it on next days. Thanks.
