### ISSUE TITLE
[Feature] A command to rename the filename

### ISSUE THREAD

**Issue by huyz** [Snezhig/obsidian-front-matter-title#34]
I'd like to be able to rename the file but clicking on the title doesn't work.

It seems the only way is to click on the Explorer and right-click on a file and choose the Rename menu item?  I can't even find a built-in command in the command palette to do that. Or maybe there's another way?

If not, could a command (that I can assign to a shortcut) be added so that I can easily rename a file?

**Comment by Snezhig** [comment]
Renaming by clicking on the title (header) is disabled if you enable `leaf's header titles`.
![image](https://user-images.githubusercontent.com/3987716/179732642-ba8b82c3-4ba9-45e6-be0b-fa7e81d16282.png)

This plugin is not about renaming files and any affect on them. 

But there are some problem with common renaming logic and I think about the way to solve them.

Thank you for the feedback.

**Comment by Snezhig** [comment]
Hello, @huyz, you can try [1.7.0-beta](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/1.7.0-beta) release, using [BRAT](https://github.com/TfTHacker/obsidian42-brat).
This release allows you to rename file by clicking on header.

**Comment by huyz** [comment]
I did as you said and disabled `leaf's header titles` and that works well for me as I don't use the Obsidian graph at all (I've always found it useless—dunno why everyone raves about it lol)

**Comment by Snezhig** [comment]
This option does not affect on graph, only on a header of a leaf. So, we can close this issue or you have any questions?

**Comment by huyz** [comment]
Yes we can close it.

Thanks for your help!
