### ISSUE TITLE
[Bug] File name is renamed when using Templater

### ISSUE THREAD

**Issue by racy2020** [Snezhig/obsidian-front-matter-title#35]
When using Templater plugin to create a file, the filename will be synchronized to the specified field after creating.

Version: 1.6.0
Obsidian Version: v0.15.6
OS: Win10

The simplest way to reproduce this bug:
1. turn on the plugin and Templater plugin, turn on Show-Current-File-Path for monitoring
2. setting Front-Matter-Title:
    1. Front matter title path: `aliases`
    2. List value behaviour: Use first value
3. create a template file as ↓ :
```
---
aliases: [ "the-note-title" ]
---
```
3. run command: `Templater: Create new note from template` and select ↑ .
4. filename will be changed to the value of aliases ("the-note-title").

**Comment by Snezhig** [comment]
Hi!
Thank you for the feedback.
I suppose that this bug appears when `leaf's` header titles` is enabled.
You can disable this feature until I find the way to solve it.

**Comment by Snezhig** [comment]
Hello, @racy2020 , you can try [1.7.0-beta](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/1.7.0-beta) release, using [BRAT](https://github.com/TfTHacker/obsidian42-brat).
It fixes the bug and allows you to rename file by clicking on header.

**Comment by racy2020** [comment]
Yes, the bug is fixed on 1.7.0-beta, thanks!! 👏
