### ISSUE TITLE
[Feature Request] Automatically create new file with Unique note creator core plugin and link alias in original note

### ISSUE THREAD

**Issue by Trikzon** [Snezhig/obsidian-front-matter-title#37]
When creating notes in Obsidian, it's common to create links to notes that haven't been created yet.

These links can be clicked on to create a note with the file name of the link.

However, it would be nice if clicking on a link to a note that hasn't been created would instead create a file using the `Unique note creator` core plugin, with the metadata set to have the correct front matter title, and the link having an alias of the title.

## Example
Clicking on the following link to a not yet created file: `[[Test Note]]`

would create the following file: `202207250239.md`

with the following contents (that should be customizable via a template):
```
---
title: 'Test Note'
---
```

and the link clicked on should become `[[202207250239|Test Note]]`.

Also, this feature would make the most sense if #18 is added.

**Comment by Snezhig** [comment]
Hi!
Have you tried to use [Templater](https://github.com/SilentVoid13/Templater). I think it can help you to realize what you want to.

**Comment by Trikzon** [comment]
Closing because unnecessary.

**Comment by Trikzon** [comment]
For anyone else finding this issue, today I found a blog post that explains how to do exactly what I wanted:
https://yelling-at-clouds.gq/a-sane-way-to-handle-zettelkasten-ids-in-obsidian/
