### ISSUE TITLE
[Feature Request] Also hide filenames in search window and autocomplete for links

### ISSUE THREAD

**Issue by XobSod** [Snezhig/obsidian-front-matter-title#38]
Great plugin !!
After installing I found out that in the search window, and autocomplete for  [[]] links, still filenames are shown. Is it possible to replace it there too?

**Comment by Snezhig** [comment]
Hi, thank you for the feedback.
I have the task about supporting search window.
Also I suppose that you talk about #18 request.

**Comment by XobSod** [comment]
Yes, that is correct, I was so hyped so I didn't notice you already have this covered ;) you may close this one.

**Comment by jpstone** [comment]
It looks like searching by title was added, but it doesn't seem like the title _replaces_ the filename...the filename still shows up, just underneath the title. Is there a way to enable an option to hide filenames altogether?
