### ISSUE TITLE
[Bug] "Enable leaf's header titles" setting has incorrect description.

### ISSUE THREAD

**Issue by Trikzon** [Snezhig/obsidian-front-matter-title#39]
The "Enable leaf's header titles" setting has the same description as the "Enable graph titles" setting.

https://github.com/Snezhig/obsidian-front-matter-title/blob/master/src/Settings.ts#L128

**Comment by Snezhig** [comment]
Wow, my mistake. Thank you. I will correct the description.

**Comment by Snezhig** [comment]
Changed in [1.7.1](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/1.7.1)
