### ISSUE TITLE
[Bug] Plugin Supercharged Links doesn't affect files with a front matter title

### ISSUE THREAD

**Issue by Trikzon** [Snezhig/obsidian-front-matter-title#40]
The plugin [Supercharged Links](https://github.com/mdelobelle/obsidian_supercharged_links) allows you to change the color of note titles depending on criteria such as what tags a note has.

Without obsidian-front-matter-title enabled:
![image](https://user-images.githubusercontent.com/29845000/184575438-ef56d1ef-55da-441f-b021-e90d95fad56a.png)

With obsidian-front-matter-title enabled:
![image](https://user-images.githubusercontent.com/29845000/184575479-b3fed2b8-0d62-46a6-8491-80d357c72694.png)

A weird, but notable, side effect is that if you disable obsidian-front-matter-title and re-enable it, the files retain their colors. Maybe this could be used somehow to implement a hacky fix if a real fix isn't feasible.

**Comment by Snezhig** [comment]
Hi.
It is difficult to say what the problem without seeing plugin code and debug. 
I will try to find some time for it.

**Comment by Trikzon** [comment]
Strange discovery. Moving a file to a different folder also fixes the color. However, restarting Obsidian removes the color again.

**Comment by gbiagini** [comment]
As referenced [here](https://github.com/Snezhig/obsidian-front-matter-title/issues/42#issuecomment-1221638357), a delay of 1000ms (1s) is sufficient to allow the Supercharged Links to persist in the Front Matter Titles.

@Snezhig has made this feature available in the current [beta](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/2.0.0-beta), available via [BRAT](https://github.com/TfTHacker/obsidian42-brat).

**Comment by Snezhig** [comment]
@Trikzon here is [2.0.0 release](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/2.0.0).
Does delay option solve your problem?

**Comment by Trikzon** [comment]
I just updated and, after realizing I had to configure it for the 1000 ms delay, it works! I'm satisfied with this and will open a different issue if anything else comes up with it.
