### ISSUE TITLE
[Feature Request] Get title from markdown headers

### ISSUE THREAD

**Issue by Shinigami072** [Snezhig/obsidian-front-matter-title#41]
Great plugin but it would be even better if it was possible to get the title from h1 header. 

It could be done by exposing them in the templates 
But the I think the best solution would be for the titles to be chosen with a fall back like this: 

1. Frontmatter title 
2. Header 
3. Filename

**Comment by Snezhig** [comment]
Hello.
You issue seems similar with #33.
I have thought about  header support, but not as fallback. 
Also this made me think about fallback template or dynamic numbers of template with order.

**Comment by Snezhig** [comment]
Hi, you can try [ beta version 2.0.0](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/2.0.0-beta), using [BRAT](https://github.com/TfTHacker/obsidian42-brat). 
It brings heading support and fallback option.

**Comment by Snezhig** [comment]
@Shinigami072 here is [2.0.0 release](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/2.0.0).
