### ISSUE TITLE
[Bug] composite template not working with version 2.0.0

### ISSUE THREAD

**Issue by edentsai** [Snezhig/obsidian-front-matter-title#43]
Hi, I installed Front Matter Title 2.0.0 from community plugins,
the composite template feature is not working well:

![2022-08-26-174030-Obsidian](https://user-images.githubusercontent.com/5071526/186876176-f0e0aa53-47d2-40aa-9889-e2b6fad93f78.png)

here is my file content:

```markdown
---
# basename: 2022-08-25-daily-note
title: "2022-08-25, Thursday, Daily Note"
---
```

configure `Template: title`, it works well:

![2022-08-26-173429-Obsidian](https://user-images.githubusercontent.com/5071526/186874967-8eba11e7-2c5e-459b-8e64-64185ab374e4.png)

![2022-08-26-173706-Obsidian](https://user-images.githubusercontent.com/5071526/186875453-072a8ada-8abf-4bb9-8701-3822667471bd.png)

configure `Template: {{title}}`, it will display `undefined` on File Explorer title:

![2022-08-26-173639-Obsidian](https://user-images.githubusercontent.com/5071526/186875367-dd90cabc-e33c-434e-b8a8-a0037b427601.png)

![2022-08-26-173618-Obsidian](https://user-images.githubusercontent.com/5071526/186875303-90f24833-d6dd-47ed-9bac-c2a330c3bfa5.png)

acutally, I want to set path template to `{{title}} | {{_basename}}`, but it is not working.

---

thanks for this awesome plugin 👍

**Comment by edentsai** [comment]
When it failed, the console display errors like this:

![2022-08-26-175041-Obsidian](https://user-images.githubusercontent.com/5071526/186878180-744ffc21-3a68-4a06-9ad8-561b9584ae07.png)

**Comment by Snezhig** [comment]
@edentsai Wow, I have lost the decorator. Sad.
I will fix it, thank you.

**Comment by Snezhig** [comment]
@edentsai you can update plugin.

**Comment by edentsai** [comment]
It works with version 2.0.1.

thank you @Snezhig
