### ISSUE TITLE
FR: preview title bar

### ISSUE THREAD

**Issue by Cammagno** [Snezhig/obsidian-front-matter-title#44]
If possible, pleas enable the title substitution also in the simple preview title bar (it already works in the Hover Editor title bar).

**Comment by Snezhig** [comment]
Hi. I am sorry, but I did not get the idea. May be you can give some screenshots?

**Comment by Cammagno** [comment]
> Hi. I am sorry, but I did not get the idea. May be you can give some screenshots?

Sure!

![image](https://user-images.githubusercontent.com/95725064/187999004-88c15e90-d71e-4454-bdbb-99e27929e28d.png)
these are the options settings

![image](https://user-images.githubusercontent.com/95725064/187998468-183d9c4d-ad24-4281-a5ca-a68a224c372d.png)
as you can see here, hovering over a link to the note, the title of the preview window is the real title, not the frontmatter one (which instead is correctly used in the title bar of the linked note)

![image](https://user-images.githubusercontent.com/95725064/187998766-c6c13b09-39b9-4a8b-89da-569709349c2f.png)
here you can see that instead, activating the preview window as hover editor, the title shown in the hovber editor windows is correctly the frontmatter one.

**Comment by Snezhig** [comment]
Look difficult, but I  will check if it is possible.
How to do this? I think that I do not know all obsidian's functional. Can you give me an example of document?

**Comment by Cammagno** [comment]
> How to do this? I think that I do not know all obsidian's functional. Can you give me an example of document?

Just to try to be sure that I'm clear enough:
I'm speaking of the div.popover.title in div.popover.titlebar, that is not updated with the frontmatter title, while 
the div.view-header-title it's correctly updated by the plugin.

This happens in whichever document, it's the title of the window that appears hovering over a link.

**Comment by Trikzon** [comment]
> How to do this? I think that I do not know all obsidian's functional. Can you give me an example of document?

@Cammagno is using Obsidian's embedded notes feature.

So for example, you have one note `test1.md`:
```md
---
title: 'Hello World'
---

Hello
```

and another file `test2.md`:
```md
![[test1]]
```

When rendered in live preview or reading mode, `test2.md` will contain a view into `test1.md`

**Comment by Cammagno** [comment]
Nope.
It is a simple link.
And the preview window I'm speaking of is the one obtained hovering on the
link.
Depending on your option settings, you may have Ctrl+hover.

Il ven 9 set 2022, 07:47 Dion Tryban ***@***.***> ha scritto:

**Comment by Trikzon** [comment]
Oh, I misread your issue. It looks like you're using the [Hover Editor](https://github.com/nothingislost/obsidian-hover-editor) plugin. That or your theme provides its features itself.

Without that plugin, my theme doesn't give hovering previews a title (or the buttons visible on it in your images).

**Comment by Cammagno** [comment]
Yes, the buttons are due to the Hover Editor plugin. Instead the title of hovering preview is there also when HE is disabled, but it may be it's provided by the ITS Theme, I diodn't knew it was not in vanilla Obsidian

**Comment by Snezhig** [comment]
I'm gonna close this issue. Feel free to open new if you need.
