### ISSUE TITLE
Bug: 2.0.0 curly brackets not working

### ISSUE THREAD

**Issue by Cammagno** [Snezhig/obsidian-front-matter-title#45]
Hi,
while simple template works without any problem, when using curly brackets stops working for me (even if I use them for a single field; it does not matter if the field value is defined in frontmatter with ', ", or without any).

working:
![image](https://user-images.githubusercontent.com/95725064/187633237-d3b2d39f-7aae-48ce-8323-8f48c5acd59f.png)

not working:
![image](https://user-images.githubusercontent.com/95725064/187632755-91a44d4e-5093-4c5e-a349-809fa2ea26f2.png)

**Comment by edentsai** [comment]
It was fixed with 2.0.1

See https://github.com/Snezhig/obsidian-front-matter-title/issues/43

**Comment by Cammagno** [comment]
> It was fixed with 2.0.1

I confirm this, thanks a lot for the plugin and the quick fix!

**Comment by Cammagno** [comment]
> @Cammagno, can we close this issue or you still have questions?

I'm totally ok with closing it, thanks!
