### ISSUE TITLE
[FR] Add support for starred plugins

### ISSUE THREAD

**Issue by Lisandra-dev** [Snezhig/obsidian-front-matter-title#46]
I will love to display alias in the plugin (official) star.

For the moment, original filename are displayed instead of the aliased name. 

![image](https://user-images.githubusercontent.com/30244939/187924397-35a5d57a-efe3-42a5-b3ed-0547f6ca1815.png)
As you can see : 
- The original filename is temporaire.md
- The displayed name is `tempo`
- But in the star pannel, it's the real name that is displayed. 

Also, as I am in 0.16, I notice that the new tab use the filename instead of the alias/title file.

**Comment by Snezhig** [comment]
Hi. I did not know about Star Plugin, but I will check if I add feature to support it.

**Comment by Lisandra-dev** [comment]
Supercharged works in starred plugin, so you can take a look in it ?

**Comment by Snezhig** [comment]
@Lisandra-dev, yea, I will add it in my queue.

**Comment by Snezhig** [comment]
@Lisandra-dev I have checked this feature. It is possible to add so I hope to do it soon.

**Comment by Snezhig** [comment]
@Lisandra-dev starred plugin support has been added in 2.3.0.
