### ISSUE TITLE
[Investigating] Console error on obsidian app loading

### ISSUE THREAD

**Issue by Evelf** [Snezhig/obsidian-front-matter-title#47]
I have an error in the console log that seems to come from front-matter-title: [obsidian.md-1662040620631.log](https://github.com/Snezhig/obsidian-front-matter-title/files/9470544/obsidian.md-1662040620631.log). It may or may not be related to #30 

I'm going to check my vault .md files, try to reproduce this error on a fresh vault, and give feedback here :)

**Comment by Snezhig** [comment]
Hi. That is difficult to say where is the problem. Do you have errors without any problems or something does not work?

**Comment by Badwolf369** [comment]
I'm having the same error and it is causing the plugin to not have any effect on the graph or explorer

**Comment by Snezhig** [comment]
@Badwolf369 do you know how to reproduce this error?

**Comment by Badwolf369** [comment]
It happens every time obsidian loads all the plugins. I was able to get it to reload the plugins by opening the inspect window, switching to the console tab and hitting CTRL+R

**Comment by Badwolf369** [comment]
I also tested and it isn't a conflict with other plugins because the same error happens on a fresh vault with only front matter title

**Comment by Snezhig** [comment]
That is strange because I do not have any errors. Can you give me a screenshoot with settings?

**Comment by Badwolf369** [comment]
![image](https://user-images.githubusercontent.com/22065391/189495457-f18c80a3-e34c-49e8-bef3-72724264a362.png)
![image](https://user-images.githubusercontent.com/22065391/189495472-7af25f58-ed18-4676-8561-962a87ee9a13.png)

These are the only settings I've changed. Everything else is the default

**Comment by Badwolf369** [comment]
However errors persist even with all defaults.

**Comment by Snezhig** [comment]
What is the version of app?

**Comment by Badwolf369** [comment]
0.15.9
Come to think of it an update may have been the cause of the error. I'll try rolling back to see.

**Comment by Badwolf369** [comment]
It was not an update

**Comment by Snezhig** [comment]
@Badwolf369
What is your OS?
The error is thrown by app because it does not find something that it's needed. Could you give me a video record? I have tried many cases, but I have not got any errors.

**Comment by Badwolf369** [comment]
On a whim I reinstalled discord. No more error and it works now. Maybe some files just got corrupted?

**Comment by Snezhig** [comment]
I close this issue. If you get new errors, please feel free to open new issue.
