### ISSUE TITLE
[0.16 Bug] Front matter title isn't displayed on tabs or the graph

### ISSUE THREAD

**Issue by Trikzon** [Snezhig/obsidian-front-matter-title#48]
On the latest insider version of Obsidian (0.16.1), the front matter title isn't displayed on tabs.

![image](https://user-images.githubusercontent.com/29845000/188042554-a1757b82-f334-4924-a25a-30ae7ec49aed.png)

I don't expect you to fix this until after 0.16 is publicly available, but I thought that I'd let you know :)

**Comment by Snezhig** [comment]
Thank you. I will try to prepare plugin for new version.

**Comment by QuaCKeReD** [comment]
This was exact reason I downloaded this plugin 😛 

Works brilliantly for title bar, but they are squashed together too much. New stacked tabs is amazing and with this feature added to plugin, will make navigation across open tabs amazing 😀

**Comment by Trikzon** [comment]
Just noticed that in 0.16 the front matter title also doesn't display on the graph.

![image](https://user-images.githubusercontent.com/29845000/189279153-ae755b42-133a-4f7c-b1d8-91ae1fa8bb9a.png)

Just going to add this here because I assume it'll be fixed in the same update after 0.16 comes out

**Comment by Snezhig** [comment]
@Trikzon  How can I get this version to prepare my plugin?

**Comment by QuaCKeReD** [comment]
0.16 is insider still 😟

**Comment by QuaCKeReD** [comment]
Is there anything, in terms of DOM, CSS, etc that we can provide that may help?

Happy to help test

**Comment by Snezhig** [comment]
Plugin does not parse DOM. Usually I read app.js to find places which I can use.
<details>
 <summary>App.js place</summary>

![изображение](https://user-images.githubusercontent.com/3987716/189311789-49594d6c-afa6-4a3f-81cd-72a1734aa498.png)

</details>

Also you can give me actual the following DOM part:
<details>
<summary>Header DOM </summary>

![изображение](https://user-images.githubusercontent.com/3987716/189312667-179ca255-74cb-4924-a39f-1f31290620ec.png)

<details>

**Comment by QuaCKeReD** [comment]
Hope this helps 😀 

In v0.16 there are two ways of viewing 'tabs'
1. As an unstacked tab in the app title section
2. As a 'stack' of tabs - think Andy's Sliding Panes

Both have an option to show title inside the pane view, too (see the 3 'Untitled' texts in images below)
1. Tab title
2. Tab title bar (option in settings)
3. Content title

![stacked div](https://user-images.githubusercontent.com/2767970/189353042-5b5cda05-db6c-4758-ae3e-57f00ba8794a.png)
![stacked dom](https://user-images.githubusercontent.com/2767970/189353046-c04eb46d-14ce-4fd1-b2f5-2fe762f2f12e.png)
![stacked ui](https://user-images.githubusercontent.com/2767970/189353049-338d7441-3497-4f1d-91d7-bd2a0239b9a3.png)
![unstacked div](https://user-images.githubusercontent.com/2767970/189353050-efd86ffc-d142-4bcb-a27c-2140d88cb8fa.png)
![unstacked dom](https://user-images.githubusercontent.com/2767970/189353051-11695f48-ca12-40b9-9248-34bb9fa62981.png)
![unstacked ui](https://user-images.githubusercontent.com/2767970/189353055-563647db-2a96-4e19-a62d-03dbde2505ea.png)

**Comment by Snezhig** [comment]
@Trikzon do you have any errors using 1.0.0 version?

**Comment by QuaCKeReD** [comment]
Hi,
I do - tabs dont show updated names and ,for some reason the title bar now shows path and yaml title...

**Comment by Snezhig** [comment]
@QuaCKeReD. Yes. The developers just move the header and it's a title-bar now. Tabs is a new feature, so It's not supported yet, but It will.
Do you have any problems with graph? I have only local graph working.

**Comment by QuaCKeReD** [comment]
Hi,

I don't really use graphs, so cant comment

**Comment by Snezhig** [comment]
@QuaCKeReD , @Trikzon  I'm going to close this issue. I do not see any errors with new version.
Feel free to open any new issue.
