### ISSUE TITLE
FR: working with Folder Notes

### ISSUE THREAD

**Issue by Cammagno** [Snezhig/obsidian-front-matter-title#51]
It would be nice if it will work also with Folder Notes :)
Even better if optionally.

**Comment by Snezhig** [comment]
What is the Folder Notes?

**Comment by Cammagno** [comment]
> What is the Folder Notes?

A note with the same name of a folder, displayed when clicking on the folder in the Navigation pane.
They are used to create a real hierarchy note system, because in this way you can have a note as a "subnote" of another note and so on

This is made possible by two popular plugins:
original plugin (not currently maintained): https://github.com/xpgo/obsidian-folder-note-plugin
currently maintained plugin: https://github.com/aidenlx/alx-folder-note

**Comment by Trikzon** [comment]
How should this plugin change to support folder notes? Or is it broken right now in some way?

Wouldn't you want the folder note to have the same name as the folder and folders have limits on what characters the name can contain?

**Comment by Cammagno** [comment]
Right now, if the note is made a folder note (with the plug-in enabled, to
make a note become a folder note it's enough to give it the same name of
the folder, or give the folder the same name of the note) your plugin does
not break anything, but it also doesn't work with it: the folder note keep
showing its original name everywhere (title bar, explorer pane and so on)

Il ven 9 set 2022, 07:43 Dion Tryban ***@***.***> ha scritto:

**Comment by Snezhig** [comment]
I'm thinking about providing API to get titles, because supporting many plugins it not easy.

**Comment by Cammagno** [comment]
> I'm thinking about providing API to get titles, because supporting many plugins it not easy.

it could be a good idea :)

**Comment by tbdcit** [comment]
> I'm thinking about providing API to get titles, because supporting many plugins it not easy.

I think this could be a very good solution. I noticed that the plugin is also not working with https://github.com/mdelobelle/obsidian_supercharged_links which also changes the way that links appear in the sidebar. I imagine that writing in support for lots of different plugins will quickly become very difficult to maintain.

**Comment by Snezhig** [comment]
There is alpha version of API. 
https://github.com/Snezhig/front-matter-plguin-api-provider
After some tests I update my plugin to return API for this package.

**Comment by Snezhig** [comment]
@Cammagno 
There is a new version of [api provider](https://www.npmjs.com/package/front-matter-plugin-api-provider).
