### ISSUE TITLE
[FR] Option for display of filename/yaml

### ISSUE THREAD

**Issue by QuaCKeReD** [Snezhig/obsidian-front-matter-title#52]
Hi,

It would be great if there was an option to decide what was displayed as the title of file.

Currently, for panes/tabs this is;
`filename (yaml)`

It would be good if this could be any combination of filename and yaml, i.e.;
`yaml (filename)`
`yaml`
etc.

**Comment by Snezhig** [comment]
Hi.
Have you tried to set a template like `{{yaml}} {{_basename}}`
See the [examples](https://github.com/Snezhig/obsidian-front-matter-title#examples);

**Comment by QuaCKeReD** [comment]
Almost 😀 

Doesnt overwrite the tab title, just changes what is appended to it

![CleanShot 20220909 140020 LIohBWH3](https://user-images.githubusercontent.com/2767970/189355639-6cc68f4a-7336-4bec-90d3-9c8805ac2470.png)

**Comment by Snezhig** [comment]
Do we speak about 0.15.9 version of app? If you use 0.16+, it breaks plugin for now.

**Comment by QuaCKeReD** [comment]
Yes, this is 0.16+

**Comment by Snezhig** [comment]
So we just have to wait the release, because I do not have this version to test any changes in my plugin.

**Comment by Snezhig** [comment]
Seems like a duplicate: #48
