### ISSUE TITLE
Feature request: enable in backlinks and search

### ISSUE THREAD

**Issue by tbdcit** [Snezhig/obsidian-front-matter-title#56]
Fantastic plugin, thank you very much!

Would it be possible to have the title displayed in the backlinks and in the search section?

**Comment by Snezhig** [comment]
Thank you for the feedback.

This issue is the same as #38?

**Comment by tbdcit** [comment]
Almost, I did not notice that https://github.com/Snezhig/obsidian-front-matter-title/issues/38 already mentioned the search aspect. 

It would also be great to have the titles appear in the backlinks

![image](https://user-images.githubusercontent.com/46998094/193770716-73b9ce45-2540-4538-9b62-554a581db09d.png)

**Comment by Snezhig** [comment]
I will check if it is possible.

**Comment by Snezhig** [comment]
@tbdcit search support has been added. If the another part of your issue is still relevant, please make a new issue.
