### ISSUE TITLE
[Feature Request] Compatibility with In-File Header & Alternative File Tree Display

### ISSUE THREAD

**Issue by julroger2013** [Snezhig/obsidian-front-matter-title#6]
This plugin works extremely well—exactly as you have indicated it should! I simply have two small feature requests. 

First, it would help if the modified title display also applied to the header automatically displayed at the top of any given note, which at present still displays the ordinary file name. 

Second, it would be terrific if your plugin also changed the title display in the Alternative File Tree plugin, which I tend to use in place of the built-in Obsidian File Explorer

**Comment by Snezhig** [comment]
Thanks for feedback.
I will think about this features, but I can not promise to realize them soon.
Also, could you give here lint to plugin you use?

**Comment by julroger2013** [comment]
Of course! The link to the File Tree Alternative Plugin is right here: https://github.com/ozntel/file-tree-alternative

Thank you for making this plugin. It really is very helpful!

**Comment by Snezhig** [comment]
Hi, you can try the [beta version](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/1.3.0-beta).
I have added the functional to display file header from front matter.

**Comment by julroger2013** [comment]
You are AMAZING! It works perfectly.

**Comment by Snezhig** [comment]
Hi, I am closing this issue. If you are still needed in Alternative File Tree support, create new issue please.
