### ISSUE TITLE
'Quick switches title' option breaks Quick Switcher

### ISSUE THREAD

**Issue by kslstn** [Snezhig/obsidian-front-matter-title#63]
Hey there, I love this plugin, especially for notes with special characters. But after updating Obsidian to 1.0.0 and the plugin to the current version, I discovered that the Quick Switcher's search didn't work anymore.

## Steps to reproduce
1. Open Quick Switcher with CMD+O
2. Enter a note name

## Exected behavior
I'd expect the Quick Switcher to show notes matching the search query to show up.

## Actual behavior
The list of notes remains static with the 10 last opened files.

## Workaround
Disable the 'Quick switches title' in the plugin settings.

**Comment by Snezhig** [comment]
Hello.
I have checked it. Do you mean that Quick Switcher Manager works only for the first 10 elements you see when you open the modal window and does not work when you type anything?

**Comment by kslstn** [comment]
That's correct!

**Comment by Snezhig** [comment]
@kslstn the bug have to be fixed in 2.5.0 version. Feel free to reopen the issue or open a new one in case you have a problem.
