### ISSUE TITLE
Alias is overridden for link autocompletion

### ISSUE THREAD

**Issue by freddyheppell** [Snezhig/obsidian-front-matter-title#68]
If I create a note (actual filename "My Second Note" in this example)

```
---
title: An Overriden Title
aliases: [alias]
---
```

and then in a second note start typing `[[alias]]`, the name of the alias is replaced with my frontmatter title:

![image](https://user-images.githubusercontent.com/1475568/201328133-b3a4afb5-1988-493d-baf0-83a8f7d7354e.png)

You can see that it's bolding the first 5 characters of the title as if it says "alias".

If I disable the plugin, I get the name of the alias I'm typing

![image](https://user-images.githubusercontent.com/1475568/201328234-d794e3ba-6716-4960-a68f-1e01ed606cff.png)

I think the correct behaviour should be to replace the note title below but keep the alias name, if that's possible?

Obsidian version: 1.0.3
Plugin version: 2.5.0
Plugin config: Template `title`, fallback `#heading`, all managers and features enabled

**Comment by Snezhig** [comment]
Do you have Quick Switcher Manager enabled? I think it is why you can see such behaviour.
Also it seems like something that I can fix.

**Comment by freddyheppell** [comment]
That seems to be it - if I disable the quick switch manager it shows the alias name.

**Comment by Snezhig** [comment]
@freddyheppell Yes. It has a condition that allows it to replace aliases. I will fix it.

**Comment by Snezhig** [comment]
@freddyheppell do you have this problem on last version?

**Comment by freddyheppell** [comment]
Sorry, forgot about this issue! Is working fine now
