### ISSUE TITLE
FR: an option for automatically sync first heading to frontmatter title

### ISSUE THREAD

**Issue by edentsai** [snezhig/obsidian-front-matter-title#69]
If possible, hopes to support a feature for automatically sync the first heading to frontmatter's `title` with quote or not.

## Feature

- A feature to automatically sync the first heading (H1 or H2 or H3 or ... or H6) to frontmatter's `title` on save file:
    - Use first H1 heading as frontmatter title.
    - or use first H2 heading as frontmatter title when there are no H1.
    - or use first H3 heading as frontmatter title when there are no H1..H2.
    - or use first H4 heading as frontmatter title when there are no H1..H3.
    - or use first H5 heading as frontmatter title when there are no H1..H4.
    - or use first H6 heading as frontmatter title when there are no H1..H5.
    - or skip sync when there are no any H1..H6 heading.
- An option for always quote frontmatter title's value or not.
- No sync first heading to the filename.

but this feature could be complex when the first heading contains some Markdown or HTML syntax
(ex: Markdown URL link, `<br/>`)...

## Example:

Case 1: sync the first heading with H1 to frontmatter's `title`.

```markdown
---
# sync the first heading `# The first heading is H1` 
# to frontmatter's title.
title: "The first heading is H1"
---

# The first heading is H1

- When The first heading is H1.
```

Case 2: sync the first heading H3 when there is no any H1 and H2 

```markdown
---
# sync the first heading `### The first heading is H3` 
# to frontmatter's title.
title: "The first heading is H3"
---

### The first heading is H3

- The first heading is H3 when there are no H1 and H2.
```

and so on...,
sync the first heading (H1 or H2 or H3 or ... or H6) to frontmatter's title.

thanks.

**Comment by Snezhig** [comment]
Hi. It seems possible to realise through metadata cache.

**Comment by snezhig** [comment]
I close this issue, because I do now have enough time to realize it. Feel free to reopen if it is actual.
