### ISSUE TITLE
Duplicate results in Quick Switch

### ISSUE THREAD

**Issue by pat-richter** [Snezhig/obsidian-front-matter-title#70]
Hey Snezhig,

thanks for the latest updates! Again!

I have some files which filenames matches one of the aliases. In the quick switcher (also tested with Quick Switcher++), I see the result two times:
1. for the file name
2. for the forwarding alias

It would be nice if one could exclude the "file" result, when a similar "alias" match is in the list.

I'm not sure if this has to be fixed within your plugin, so please give me a hint if I should report this on another place.

![Obsidian Quick Switcher](https://user-images.githubusercontent.com/1271059/202922014-4b021952-22c9-4708-9ad1-3691e9b76d66.png)

![QuickSwitchter++](https://user-images.githubusercontent.com/1271059/202922007-873e1039-f685-4388-ab05-bfb5348d8666.png)

**Comment by Snezhig** [comment]
Hi. 
Did this happen on 2.5.0 version of plugin or 2.6.0-beta?
It has some problems with QuickSwitcher on 2.5.0.

**Comment by pat-richter** [comment]
Has been with 2.5.0, but I've  updated to 2.6.0 now and it's still the case.

Not sure if this has been an issue before, I've restructured my vault files.

**Comment by Snezhig** [comment]
Could you give me an example that produces such behaviour?

**Comment by pat-richter** [comment]
[Jos 4,1 – 5,1.md](https://github.com/Snezhig/obsidian-front-matter-title/files/10082938/Jos.4.1.5.1.md)

I've uploaded the file. The filename is "Jos 4,1 – 5,1.md", maybe it has been changed from github

**Comment by Snezhig** [comment]
Also could you give me plugin's settings? What the path is? What features are enabled?

**Comment by pat-richter** [comment]
Hi, thanks for the response. The file path is "/media/space/Drive/Studium/Obsidian/10 Bibel/6_Jos/Jos 4,1 – 5,1.md"

I have all settings enabled, using "aliases" > "first value", nothing is blacklisted.

I've played around with the alias title strategy, will upload some images, named by strategy.

There are also differences when I switch between them (has adjust as default, but see the change in the "replace to adjust" image...) This fixes itself after restarting Obsidian.

adjust (missing: Jos 4,1 – 5,1)
![adjust](https://user-images.githubusercontent.com/1271059/204327338-982899b6-2b84-4174-96c4-6ebe1be0b4de.png)


ensure (missing: Jos 4,1 – 5,1)
![ensure](https://user-images.githubusercontent.com/1271059/204327345-76e32684-2e74-4928-9a3c-18e97895e995.png)

replace 
![replace](https://user-images.githubusercontent.com/1271059/204327333-7fff5fce-9c53-4703-bed2-6181e80644fc.png)

switching from replace to adjust
![switching from replace to adjust](https://user-images.githubusercontent.com/1271059/204327323-e0da1cd0-d5ac-412d-aa69-b6b1904b3fee.png)

**Comment by Snezhig** [comment]
Sorry but I'm confused a little.
It's only one problem that the settings do not change properly until you reload the app?
The plugin has  confusing logic with settings changing. I'm working on it.

**Comment by Snezhig** [comment]
I'm going to close this issue. Feel free to reopen it, if it's needed or create a new one.
