### ISSUE TITLE
Compatibility with some other plugins

### ISSUE THREAD

**Issue by antomonte** [Snezhig/obsidian-front-matter-title#71]
Hi!

This plugin is making things much easier!

I'd like to suggest adding compatibility with:

- Stacked tabs -> so far it doesn't apply the title change

![image](https://user-images.githubusercontent.com/5910/203118526-a20a6575-1a26-492a-b3cb-823b0254ad90.png)

- Folder Notes -> notes which are converted to folders do not show title at file navigator, not even notes which are inside such folders

![image](https://user-images.githubusercontent.com/5910/203118574-fc728a69-b85f-4f39-88e6-28a1b55eab2a.png)

- Hover Editor -> hovered notes currently do not show the title

![image](https://user-images.githubusercontent.com/5910/203118598-40c81d0f-7c92-463a-90a4-27d1ac161263.png)

- Note Refactor -> popup window doesn't show new titles. By now only works writing the real filename (in my case YYYYMMDDHHmm)

Best regards,
Antonio Montesinos

**Comment by mkasu** [comment]
I'd like to add Dataview to this list:

E.g., this folder:
![CleanShot 2022-11-24 at 10 40 23@2x](https://user-images.githubusercontent.com/798036/203675282-5b0490bc-e29f-4188-bb21-df56f8406db9.png)

Is displayed as
![CleanShot 2022-11-24 at 10 40 28@2x](https://user-images.githubusercontent.com/798036/203675310-a52609c8-6247-4223-a6b5-fe1c4ce4c5f5.png)

In a simple list dataview embed:
<img width="163" alt="CleanShot 2022-11-24 at 10 40 34@2x" src="https://user-images.githubusercontent.com/798036/203675329-60d44433-394d-493a-9e2b-19d3edccb762.png">

(Same behavior for tables)

**Comment by Snezhig** [comment]
Stacked tabs - is application's feature, so I will check if it is possible to support.
But another is community plugins and it's to difficult to support them.
But, you can make authors know about [api provider](https://www.npmjs.com/package/front-matter-plugin-api-provider).
It provides some functions to use plugins api and it's titles.

**Comment by PiotrSss** [comment]
It also doesn't work on canvas

**Comment by vergenzt** [comment]
Just to add: I was able to display a list of frontmatter-titled notes in [Dataview](https://github.com/blacksmithgu/obsidian-dataview) by relying on the fact that this plugin updates an internal Obsidian aliases cache:

From Dataview query `LIST ...`:
![Image](https://github.com/user-attachments/assets/3e6aa6b5-3c60-45e3-afc4-9ff5e9496c20)

From Dataview query `LIST WITHOUT ID link(file.name, file.aliases[0])`:
![Image](https://github.com/user-attachments/assets/1dc897f7-dcd1-46ac-b1c4-6650767a4ebd)
