### ISSUE TITLE
Update link alias 

### ISSUE THREAD

**Issue by lilruffian** [snezhig/obsidian-front-matter-title#73]
I could’ve sworn that this plug-in automatically updated file link aliases. Was the feature removed? I can’t seem to find the option anymore.

**Comment by Snezhig** [comment]
Yes, this option has been removed recently. But I can return in in the future.

**Comment by snezhig** [comment]
Returned in [3.2.0](https://github.com/snezhig/obsidian-front-matter-title/releases/tag/3.2.0)

**Comment by vanbang9710** [comment]
Where can I turn it on in the settings? I can't find the [Note Link options "Approve"](https://github.com/snezhig/obsidian-front-matter-title/blob/master/docs/Features.md#note-link)
