### ISSUE TITLE
Cannot make composite templates with `#heading`

### ISSUE THREAD

**Issue by lyndhurst** [Snezhig/obsidian-front-matter-title#74]
I managed to make composite templates work great with any field combined in the front matter.

`{{#heading}}` works fine as well by itself, but if I add any other field from metadata like `{{#heading}} {{tags}}`, it stops working. 

Tags are displayed correctly, but `{{#heading}}` is displayed literally (verbatim), not the actual heading from file.

Thanks for your time.

**Comment by Snezhig** [comment]
Hello. 
I found the cause of the problem. So it will be solved. Thank you for the issue.

**Comment by Snezhig** [comment]
@lyndhurst Fixed in 2.7.1.

**Comment by lyndhurst** [comment]
I can confirm it is working now, thank you.
