### ISSUE TITLE
[Feature Request] Possibility to set multiple templates

### ISSUE THREAD

**Issue by lyndhurst** [snezhig/obsidian-front-matter-title#75]
Hi,

I find your plugin indispensable when using unique ids for file names, like I, and many zk style note-takers do.

However, having the possibility to add more than one template, and assign them to different "features" in the settings section using a dropdown instead of  boolean button would add even more value in my opinion.

For example, I would like to show only the "heading" in the file explorer and the tab/pane title not to clutter the ui, and save screen space, but, showing the "heading" and "tags" when performing searches would make them more effective & versatile. Other front matter fields might be more suitable depending on everyone's use case of course.

Thank you for taking the time to consider it.

**Comment by Snezhig** [comment]
Hi, the plugin has two templates: main and fallback, the second is used when the first can not be resolved,
But I guess that you want to have a setting to set a template for each feature individually?

**Comment by lyndhurst** [comment]
Exactly.
The fallback template can still fulfill the same purpose, but the ability to set a different template for each feature can be helpful to have shorter "titles" where space is missing (e.g. the file explorer), and add more fields where it is useful like searches.
