### ISSUE TITLE
Can't checkout repository on Windows (colons in file names)

### ISSUE THREAD

**Issue by mkczyk** [Snezhig/obsidian-front-matter-title#77]
I can't checkout repository on Windows:
```
$ git clone https://github.com/Snezhig/obsidian-front-matter-title.git
Cloning into 'obsidian-front-matter-title'...
remote: Enumerating objects: 4399, done.
remote: Counting objects: 100% (589/589), done.
remote: Compressing objects: 100% (230/230), done.
remote: Total 4399 (delta 317), reused 575 (delta 317), pack-reused 3810
Receiving objects: 100% (4399/4399), 2.44 MiB | 11.77 MiB/s, done.
Resolving deltas: 100% (2602/2602), done.
error: invalid path 'github/images/SearchOff.png:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
and no one file in directory.

The reason is file names with colons. Windows doesn't support this character in file names: 
- https://confluence.atlassian.com/bitbucketserverkb/error-invalid-path-during-git-clone-to-windows-client-1085186345.html 
- https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

> The following reserved characters:
> : (colon)

### First workaround (not recommended)

```
git config --global core.protectNTFS false
```
Now you can clone and checkout repository on Windows.

But it's not recommended due to security reasons ([#](https://confluence.atlassian.com/bitbucketserverkb/error-invalid-path-during-git-clone-to-windows-client-1085186345.html), [#](https://github.com/git/git/commit/9102f958ee5254b10c0be72672aa3305bf4f4704)). 

### Second workaround (insufficient)

After clone and checkout with error you can:
```
$  git checkout HEAD -- .
error: invalid path 'github/images/SearchOff.png:Zone.Identifier'
error: invalid path 'github/images/SearchOn.png:Zone.Identifier'
```
and now all files (without two with colon in names) are in repository.

But of course you can't work with those files and repo.

### Solution (rename in repository)

Please change names of those two files:
- `github/images/SearchOff.png:Zone.Identifier`
- `github/images/SearchOn.png:Zone.Identifier`

remove colons or replace with other character (for example dash `-`):
- `github/images/SearchOff.png-Zone.Identifier`
- `github/images/SearchOn.png-Zone.Identifier`

**Comment by Snezhig** [comment]
Hi, these files have been accidentally added. I removed them.

**Comment by mkczyk** [comment]
Thanks! Now it works.
