### ISSUE TITLE
Heading alias not working for notes with no YAML frontmatter

### ISSUE THREAD

**Issue by sjerdmann** [Snezhig/obsidian-front-matter-title#78]
Hi,
I'm used to name files with unique filenames with the "Unique note creator" core plugin and to set the actual note title in H1 heading. Therefore the `#heading` template is perfect for me (and thanks a lot for this !).
Yet, I'm also used to not include a YAML frontmatter in my notes and the "alias" feature does not seem to work in this configuration, regardless of the strategy. Notes with no yaml frontmatter do not appear when typing their heading in an internal link or in quick switcher.
On the other hand, creating a dummy YAML frontmatter (for example with only `key: value` as actual content) solves the problem.

**Steps to reproduce :**

- Create a new vault.
- Install the plugin
- Set "#heading" as template, and check all switches in "Features"
- Add the attached dummy notes to the vault : [2301071528.md](https://github.com/Snezhig/obsidian-front-matter-title/files/10366509/2301071528.md) and 
[2301071529.md](https://github.com/Snezhig/obsidian-front-matter-title/files/10366511/2301071529.md).
- Restart Obsidian.

With this steps, opening the quick switchter with Ctrl+O and typing "Note 1" shows "No note found". On the other hand, typing "Note 2" actually brings up the corresponding note. Same when typing `[[` to create a link.

Thanks in advance !

**Comment by Snezhig** [comment]
Hi, yes, it's skip files without frontmatter:
`return metadata.frontmatter ? this.process(metadata.frontmatter, path) : false;`
I will think about changing this logic to support files without frontmatter.

**Comment by sjerdmann** [comment]
Thanks for your reply, I didn't know if it was intended behaviour.
Indeed, it would be nice if it did not depend on files having a frontmatter. Are you open to PRs, in case I find the time to dig into this ?

**Comment by Snezhig** [comment]
@sjerdmann I just did not think that someone would have files without meta block.
I have some thought how I can change this behaviour.

**Comment by sjerdmann** [comment]
It works great now, thank you !
