### ISSUE TITLE
[Feature] Support of PDF export

### ISSUE THREAD

**Issue by ffollonier** [snezhig/obsidian-front-matter-title#80]
Hi,

It would be nice to replace the note title when we use the PDF export (with include filename as title).

I don't know if is it technically possible...

Thanks for your feedback,

Best regards,
Fred

**Comment by snezhig** [comment]
I'm not sure, if it is possible. If I have time, I will try to explore this.

**Comment by snezhig** [comment]
I did not found a way to support it. Sorry.
