### ISSUE TITLE
Could you add support for backlinks view (in notes and sidebar)?

### ISSUE THREAD

**Issue by erauner12** [snezhig/obsidian-front-matter-title#81]
First of all, thank you so much for creating this plugin! I really enjoy being able to have the best of both worlds! Unique file names at the OS level for each note, while still being able to see the alias that is kept in sync with linter.

Could you please add support for the backlinks view?

To reproduce, execute the following command: `Backlinks: Toggle backlinks in document` or `Backlinks: Show backlinks`

<img width="696" alt="image" src="https://user-images.githubusercontent.com/59383957/212436275-1d68c030-94e8-4c53-8e8d-2565e943ae2d.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/59383957/212436474-a7b404d2-a15a-4935-8472-20ad7e267894.png">

**Comment by Snezhig** [comment]
Hi, thank you for the feedback. I will try to find out if it is possible.
