### ISSUE TITLE
Please could you provide some simple example how to use your plugin?

### ISSUE THREAD

**Issue by myownstandard** [snezhig/obsidian-front-matter-title#85]
I think i understood the main concept of the plugin - we can replace File Name text with some other text (at least display it in File Explorer).
Also i understand how to use Yaml frontmatter in Obsidian.
But step-by-step guide will be very helpful - what we need to do next? Create some string value in Yaml frontmatter (where we need to put that value)?
For non-nerdy guys like me.
Thank you! 🙏

**Comment by Snezhig** [comment]
HI. It's a good idea to create something like a tutorial, but this requires some time.
The plugin can work with Yaml and Headings. If you use Yaml you can store a value where you want. Only thing you have to do is to tell plugin a path to your value. You can see [examples](https://github.com/Snezhig/obsidian-front-matter-title#examples)

**Comment by myownstandard** [comment]
🤯Maybe i made smthg wrong?
![2023-01-28_16-18-13](https://user-images.githubusercontent.com/78643199/215268709-4b412f32-bff5-4bfd-a1ad-21b16d8f44ee.png)

**Comment by snezhig** [comment]
What do you have here?
![изображение](https://user-images.githubusercontent.com/3987716/215271681-ac8d5396-258c-4263-b1f9-e6b0755d0e66.png)

**Comment by myownstandard** [comment]
I didn`t touch it... Do i need to change something there?
![2023-01-28_18-42-53](https://user-images.githubusercontent.com/78643199/215275716-0d839526-f939-4f39-9c3d-2e3378aaab7d.png)

**Comment by snezhig** [comment]
Yes. You have to tell plugin the path.
"title" - means that plugin will look for a key "title" in first level of your meta block.
Also you can set it like "additional.title". That tells plugin to look for "title" key in "additional" key in first level.

**Comment by myownstandard** [comment]
Wow! It is fantastic plugin! Thank you! I think it will become even more popular if you will add that simple explanation (for newbies like me) that you gave to me..Thank you!
