### ISSUE TITLE
Add support for .mdx files

### ISSUE THREAD

**Issue by johnzanussi** [snezhig/obsidian-front-matter-title#88]
Would it be possible to enable this plugin for [`.mdx` files](https://mdxjs.com/)?

I (and others) use plugins like [`mdx-as-md`](https://github.com/mkozhukharenko/mdx-as-md-obsidian) to add `.mdx` support.

**Comment by snezhig** [comment]
I'm not familiar with it. If it has the same yaml block and obsidian app caches its metadata, then it would be possible. I can explore this.

**Comment by johnzanussi** [comment]
Thanks!

MDX files are almost a one-to-one match of normal markdown files except they allow for including additional JavaScript/TypeScript code. The blog posts on my personal website are populated via MDX files. You can take a look at them on [my GitHub](https://github.com/johnzanussi/johnzanussi.com/tree/main/_posts). You'll notice there isn't much difference at all from regular Markdown files except for a few small use cases where I am importing components from my repo into MDX.

https://github.com/johnzanussi/johnzanussi.com/blob/main/_posts/3d-printer-psu-control.mdx?plain=1#L67

**Comment by snezhig** [comment]
So, It seems to be possible, but not easy.

**Comment by johnzanussi** [comment]
I poked around the code for your plugin a bit and came to the same realization. I would have opened a PR otherwise. 😎

**Comment by snezhig** [comment]
I close this issue, because I do now have enough time to realize it. Feel free to reopen if it is actual.
