### ISSUE TITLE
Files view not updated on paste

### ISSUE THREAD

**Issue by haroldship** [snezhig/obsidian-front-matter-title#89]
When I copy/paste a title from (for example) the 'alias' field, the files view is not updated and still shows the actual filename. If I close/reopen the note, it still does not update.

After I make a change to the pasted title it updates ok.

Also occurs if I create the note on my iPhone. I use iCloud synchronization.

**Comment by snezhig** [comment]
Does you use macOs? I have heard that plugin has some problem with this platform.

**Comment by haroldship** [comment]
Yes, I use MacOS Ventura 13.1 on a Macbook Pro 2016 (intel).

**Comment by snezhig** [comment]
Okay, I will try to find out the problem.

**Comment by snezhig** [comment]
@haroldship did you mean that plugin does not work in case you rename a file?

**Comment by haroldship** [comment]
No, I don't rename a file. I use the "Unique file" plugin which used to be
the Zettelkasten plugin. The filenames are generated according to the
pattern YYYYMMDDhhmmss. I have a note header with alias, title and a few
other things. I usually put the logical title in the alias, then copy/paste
to the title. This used to work all the time. Lately I upgraded all my
plugins, and now the filename of the new file in the Files area still looks
like the actual filename and not the title. If I edit the title field, even
a little bit, then the Files area gets updated.

**Comment by snezhig** [comment]
Could you record a short video? I tried to copy something it meta block and plugin works correctly.

**Comment by haroldship** [comment]
Not exactly as I said, but you can see that when I move the file, it's name in Files view reverts until I change it.

https://user-images.githubusercontent.com/3765503/215714444-e0bf1f98-4dcf-42a3-bf8b-11e2e60496f5.mov

**Comment by snezhig** [comment]
Do you use 2.9.4 version? I released it yesterday. Could you update, please, and try again? If the problem reproduces, let me know.

**Comment by haroldship** [comment]
It seems ok with 2.9.4

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by snezhig** [comment]
So, I'm going to close this issue. Feel free to reopen it or create a new one.
