### ISSUE TITLE
No settings show up

### ISSUE THREAD

**Issue by jayliu50** [snezhig/obsidian-front-matter-title#95]
Amazing plugin, so thank you for your work!!

I do want to report that when I install the plugin (I'm at 3.0.0, and using Obsidian 1.1.16 on Windows), I see no settings show up on the left-hand side bar. Additionally, when I try to uninstall the plugin, it says it fails.

However, if I install v2 of the plugin, I do see all the settings, and the plugin seems to work.

**Comment by snezhig** [comment]
Thank you.
Did you have any error in console? (ctrl+shift+i)
I can check your issue in some hours.

**Comment by jayliu50** [comment]
Two things I see in there

1) 
     > Front Matter Title: styles.css not found

2) 
     > plugin:obsidian-front-matter-title-plugin:37 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'templates')
    at Ur.loadSettings (plugin:obsidian-front-matter-title-plugin:37:20963)
    at async Ur.onload (plugin:obsidian-front-matter-title-plugin:37:21904)


I also want to note that this is for a completely new install of 3.0.

I found that if I install with 2.10, allow it to create data.json, and then copy over the main.js and manifest.json, then it _seems_ to work.

**Comment by snezhig** [comment]
@jayliu50 yes, there was a error with new installations. 
3.0.1 version fixes that. 
Thank you for this issue.

**Comment by jayliu50** [comment]
Works great. Thank you so much for the fix!

And thank you again for a great plugin. The customization options are exceedingly thoughtful too.
